// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "media/media_service.proto" (package "chatnow.media", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MediaService } from "./media_service";
import type { SpeechRecognitionRsp } from "./media_service";
import type { SpeechRecognitionReq } from "./media_service";
import type { GetFileInfoRsp } from "./media_service";
import type { GetFileInfoReq } from "./media_service";
import type { ApplyDownloadRsp } from "./media_service";
import type { ApplyDownloadReq } from "./media_service";
import type { AbortMultipartRsp } from "./media_service";
import type { AbortMultipartReq } from "./media_service";
import type { CompleteMultipartRsp } from "./media_service";
import type { CompleteMultipartReq } from "./media_service";
import type { ApplyPartRsp } from "./media_service";
import type { ApplyPartReq } from "./media_service";
import type { InitMultipartRsp } from "./media_service";
import type { InitMultipartReq } from "./media_service";
import type { CompleteUploadRsp } from "./media_service";
import type { CompleteUploadReq } from "./media_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ApplyUploadRsp } from "./media_service";
import type { ApplyUploadReq } from "./media_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.media.MediaService
 */
export interface IMediaServiceClient {
    /**
     * @generated from protobuf rpc: ApplyUpload
     */
    applyUpload(input: ApplyUploadReq, options?: RpcOptions): UnaryCall<ApplyUploadReq, ApplyUploadRsp>;
    /**
     * @generated from protobuf rpc: CompleteUpload
     */
    completeUpload(input: CompleteUploadReq, options?: RpcOptions): UnaryCall<CompleteUploadReq, CompleteUploadRsp>;
    /**
     * @generated from protobuf rpc: InitMultipartUpload
     */
    initMultipartUpload(input: InitMultipartReq, options?: RpcOptions): UnaryCall<InitMultipartReq, InitMultipartRsp>;
    /**
     * @generated from protobuf rpc: ApplyPartUpload
     */
    applyPartUpload(input: ApplyPartReq, options?: RpcOptions): UnaryCall<ApplyPartReq, ApplyPartRsp>;
    /**
     * @generated from protobuf rpc: CompleteMultipartUpload
     */
    completeMultipartUpload(input: CompleteMultipartReq, options?: RpcOptions): UnaryCall<CompleteMultipartReq, CompleteMultipartRsp>;
    /**
     * @generated from protobuf rpc: AbortMultipartUpload
     */
    abortMultipartUpload(input: AbortMultipartReq, options?: RpcOptions): UnaryCall<AbortMultipartReq, AbortMultipartRsp>;
    /**
     * @generated from protobuf rpc: ApplyDownload
     */
    applyDownload(input: ApplyDownloadReq, options?: RpcOptions): UnaryCall<ApplyDownloadReq, ApplyDownloadRsp>;
    /**
     * @generated from protobuf rpc: GetFileInfo
     */
    getFileInfo(input: GetFileInfoReq, options?: RpcOptions): UnaryCall<GetFileInfoReq, GetFileInfoRsp>;
    /**
     * @generated from protobuf rpc: SpeechRecognition
     */
    speechRecognition(input: SpeechRecognitionReq, options?: RpcOptions): UnaryCall<SpeechRecognitionReq, SpeechRecognitionRsp>;
}
/**
 * @generated from protobuf service chatnow.media.MediaService
 */
export class MediaServiceClient implements IMediaServiceClient, ServiceInfo {
    typeName = MediaService.typeName;
    methods = MediaService.methods;
    options = MediaService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ApplyUpload
     */
    applyUpload(input: ApplyUploadReq, options?: RpcOptions): UnaryCall<ApplyUploadReq, ApplyUploadRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApplyUploadReq, ApplyUploadRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CompleteUpload
     */
    completeUpload(input: CompleteUploadReq, options?: RpcOptions): UnaryCall<CompleteUploadReq, CompleteUploadRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompleteUploadReq, CompleteUploadRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InitMultipartUpload
     */
    initMultipartUpload(input: InitMultipartReq, options?: RpcOptions): UnaryCall<InitMultipartReq, InitMultipartRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<InitMultipartReq, InitMultipartRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ApplyPartUpload
     */
    applyPartUpload(input: ApplyPartReq, options?: RpcOptions): UnaryCall<ApplyPartReq, ApplyPartRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApplyPartReq, ApplyPartRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CompleteMultipartUpload
     */
    completeMultipartUpload(input: CompleteMultipartReq, options?: RpcOptions): UnaryCall<CompleteMultipartReq, CompleteMultipartRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompleteMultipartReq, CompleteMultipartRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AbortMultipartUpload
     */
    abortMultipartUpload(input: AbortMultipartReq, options?: RpcOptions): UnaryCall<AbortMultipartReq, AbortMultipartRsp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AbortMultipartReq, AbortMultipartRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ApplyDownload
     */
    applyDownload(input: ApplyDownloadReq, options?: RpcOptions): UnaryCall<ApplyDownloadReq, ApplyDownloadRsp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ApplyDownloadReq, ApplyDownloadRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetFileInfo
     */
    getFileInfo(input: GetFileInfoReq, options?: RpcOptions): UnaryCall<GetFileInfoReq, GetFileInfoRsp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetFileInfoReq, GetFileInfoRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SpeechRecognition
     */
    speechRecognition(input: SpeechRecognitionReq, options?: RpcOptions): UnaryCall<SpeechRecognitionReq, SpeechRecognitionRsp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<SpeechRecognitionReq, SpeechRecognitionRsp>("unary", this._transport, method, opt, input);
    }
}
