// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "media/media_service.proto" (package "chatnow.media", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ResponseHeader } from "../common/envelope";
/**
 * @generated from protobuf message chatnow.media.FileInfo
 */
export interface FileInfo {
    /**
     * @generated from protobuf field: string file_id = 1
     */
    fileId: string;
    /**
     * @generated from protobuf field: string file_name = 2
     */
    fileName: string;
    /**
     * @generated from protobuf field: int64 file_size = 3
     */
    fileSize: bigint;
    /**
     * @generated from protobuf field: string mime_type = 4
     */
    mimeType: string;
    /**
     * @generated from protobuf field: int64 uploaded_at_ms = 5
     */
    uploadedAtMs: bigint;
}
// ===== 单段三步上传 =====

/**
 * @generated from protobuf message chatnow.media.ApplyUploadReq
 */
export interface ApplyUploadReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string file_name = 2
     */
    fileName: string;
    /**
     * @generated from protobuf field: int64 file_size = 3
     */
    fileSize: bigint;
    /**
     * @generated from protobuf field: string mime_type = 4
     */
    mimeType: string;
    /**
     * @generated from protobuf field: string content_hash = 5
     */
    contentHash: string; // "sha256:<64hex>"
    /**
     * @generated from protobuf field: chatnow.media.MediaPurpose purpose = 6
     */
    purpose: MediaPurpose;
}
/**
 * @generated from protobuf message chatnow.media.ApplyUploadRsp
 */
export interface ApplyUploadRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string file_id = 2
     */
    fileId: string;
    /**
     * @generated from protobuf field: bool already_exists = 3
     */
    alreadyExists: boolean; // true=已去重命中，无需上传
    /**
     * @generated from protobuf field: string upload_url = 4
     */
    uploadUrl: string; // presigned PUT URL（dedup 时为空）
    /**
     * @generated from protobuf field: map<string, string> headers = 5
     */
    headers: {
        [key: string]: string;
    }; // 客户端 PUT 必带的 header
    /**
     * @generated from protobuf field: int32 expires_in_sec = 6
     */
    expiresInSec: number;
}
/**
 * @generated from protobuf message chatnow.media.CompleteUploadReq
 */
export interface CompleteUploadReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string file_id = 2
     */
    fileId: string;
}
/**
 * @generated from protobuf message chatnow.media.CompleteUploadRsp
 */
export interface CompleteUploadRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.media.FileInfo file_info = 2
     */
    fileInfo?: FileInfo;
}
// ===== 分片上传 =====

/**
 * @generated from protobuf message chatnow.media.InitMultipartReq
 */
export interface InitMultipartReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string file_name = 2
     */
    fileName: string;
    /**
     * @generated from protobuf field: int64 file_size = 3
     */
    fileSize: bigint;
    /**
     * @generated from protobuf field: string mime_type = 4
     */
    mimeType: string;
    /**
     * @generated from protobuf field: string content_hash = 5
     */
    contentHash: string;
    /**
     * @generated from protobuf field: chatnow.media.MediaPurpose purpose = 6
     */
    purpose: MediaPurpose;
}
/**
 * @generated from protobuf message chatnow.media.InitMultipartRsp
 */
export interface InitMultipartRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string file_id = 2
     */
    fileId: string;
    /**
     * @generated from protobuf field: string upload_id = 3
     */
    uploadId: string;
    /**
     * @generated from protobuf field: int32 recommended_part_size_bytes = 4
     */
    recommendedPartSizeBytes: number;
}
/**
 * @generated from protobuf message chatnow.media.ApplyPartReq
 */
export interface ApplyPartReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string upload_id = 2
     */
    uploadId: string;
    /**
     * @generated from protobuf field: int32 part_number = 3
     */
    partNumber: number; // 1..10000
}
/**
 * @generated from protobuf message chatnow.media.ApplyPartRsp
 */
export interface ApplyPartRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string upload_url = 2
     */
    uploadUrl: string;
    /**
     * @generated from protobuf field: int32 expires_in_sec = 3
     */
    expiresInSec: number;
}
/**
 * @generated from protobuf message chatnow.media.PartETag
 */
export interface PartETag {
    /**
     * @generated from protobuf field: int32 part_number = 1
     */
    partNumber: number;
    /**
     * @generated from protobuf field: string etag = 2
     */
    etag: string;
}
/**
 * @generated from protobuf message chatnow.media.CompleteMultipartReq
 */
export interface CompleteMultipartReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string upload_id = 2
     */
    uploadId: string;
    /**
     * @generated from protobuf field: repeated chatnow.media.PartETag parts = 3
     */
    parts: PartETag[]; // 升序 part_number
}
/**
 * @generated from protobuf message chatnow.media.CompleteMultipartRsp
 */
export interface CompleteMultipartRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.media.FileInfo file_info = 2
     */
    fileInfo?: FileInfo;
}
/**
 * @generated from protobuf message chatnow.media.AbortMultipartReq
 */
export interface AbortMultipartReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string upload_id = 2
     */
    uploadId: string;
}
/**
 * @generated from protobuf message chatnow.media.AbortMultipartRsp
 */
export interface AbortMultipartRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
}
// ===== 下载 + 查询 =====

/**
 * @generated from protobuf message chatnow.media.ApplyDownloadReq
 */
export interface ApplyDownloadReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string file_id = 2
     */
    fileId: string;
}
/**
 * @generated from protobuf message chatnow.media.ApplyDownloadRsp
 */
export interface ApplyDownloadRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string download_url = 2
     */
    downloadUrl: string; // presigned GET URL
    /**
     * @generated from protobuf field: int32 expires_in_sec = 3
     */
    expiresInSec: number;
    /**
     * @generated from protobuf field: chatnow.media.FileInfo file_info = 4
     */
    fileInfo?: FileInfo;
}
/**
 * @generated from protobuf message chatnow.media.GetFileInfoReq
 */
export interface GetFileInfoReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string file_id = 2
     */
    fileId: string;
}
/**
 * @generated from protobuf message chatnow.media.GetFileInfoRsp
 */
export interface GetFileInfoRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.media.FileInfo file_info = 2
     */
    fileInfo?: FileInfo;
}
// ===== 短音频 ASR（v1 保留 RPC + bytes，不入 S3） =====

/**
 * @generated from protobuf message chatnow.media.SpeechRecognitionReq
 */
export interface SpeechRecognitionReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: bytes speech_content = 2
     */
    speechContent: Uint8Array;
}
/**
 * @generated from protobuf message chatnow.media.SpeechRecognitionRsp
 */
export interface SpeechRecognitionRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string recognition_result = 2
     */
    recognitionResult: string;
}
// ===========================================================================
// MediaService —— P4 媒体子系统对外契约
// ---------------------------------------------------------------------------
// 三类调用：
//   1. 单段上传（≤100MB）：ApplyUpload → 客户端 PUT presigned → CompleteUpload
//   2. 分片上传（>100MB） ：InitMultipartUpload → ApplyPartUpload * N
//                          → CompleteMultipartUpload | AbortMultipartUpload
//   3. 下载/查询           ：ApplyDownload / GetFileInfo
//   4. 短音频 ASR          ：SpeechRecognition（保留 RPC + bytes，不走 S3）
// ---------------------------------------------------------------------------
// 设计要点：
//   - 服务端不过 bytes（除 SpeechRecognition）
//   - file_id 由服务端在 ApplyUpload / InitMultipartUpload 时分配
//   - content_hash 形式 "sha256:<64 lowercase hex>"，用于去重 + 完整性
//   - 各 Req 都带 request_id；user_id / device_id 走 brpc metadata（gateway 注入）
// ===========================================================================

/**
 * @generated from protobuf enum chatnow.media.MediaPurpose
 */
export enum MediaPurpose {
    /**
     * @generated from protobuf enum value: MEDIA_PURPOSE_UNSPECIFIED = 0;
     */
    MEDIA_PURPOSE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: AVATAR = 1;
     */
    AVATAR = 1,
    /**
     * @generated from protobuf enum value: GROUP_AVATAR = 2;
     */
    GROUP_AVATAR = 2,
    /**
     * @generated from protobuf enum value: CHAT = 3;
     */
    CHAT = 3,
    /**
     * @generated from protobuf enum value: STICKER = 4;
     */
    STICKER = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class FileInfo$Type extends MessageType<FileInfo> {
    constructor() {
        super("chatnow.media.FileInfo", [
            { no: 1, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "file_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "uploaded_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<FileInfo>): FileInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.fileName = "";
        message.fileSize = 0n;
        message.mimeType = "";
        message.uploadedAtMs = 0n;
        if (value !== undefined)
            reflectionMergePartial<FileInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FileInfo): FileInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file_id */ 1:
                    message.fileId = reader.string();
                    break;
                case /* string file_name */ 2:
                    message.fileName = reader.string();
                    break;
                case /* int64 file_size */ 3:
                    message.fileSize = reader.int64().toBigInt();
                    break;
                case /* string mime_type */ 4:
                    message.mimeType = reader.string();
                    break;
                case /* int64 uploaded_at_ms */ 5:
                    message.uploadedAtMs = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FileInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file_id = 1; */
        if (message.fileId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fileId);
        /* string file_name = 2; */
        if (message.fileName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileName);
        /* int64 file_size = 3; */
        if (message.fileSize !== 0n)
            writer.tag(3, WireType.Varint).int64(message.fileSize);
        /* string mime_type = 4; */
        if (message.mimeType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.mimeType);
        /* int64 uploaded_at_ms = 5; */
        if (message.uploadedAtMs !== 0n)
            writer.tag(5, WireType.Varint).int64(message.uploadedAtMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.FileInfo
 */
export const FileInfo = new FileInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyUploadReq$Type extends MessageType<ApplyUploadReq> {
    constructor() {
        super("chatnow.media.ApplyUploadReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "file_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "content_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "purpose", kind: "enum", T: () => ["chatnow.media.MediaPurpose", MediaPurpose] }
        ]);
    }
    create(value?: PartialMessage<ApplyUploadReq>): ApplyUploadReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.fileName = "";
        message.fileSize = 0n;
        message.mimeType = "";
        message.contentHash = "";
        message.purpose = 0;
        if (value !== undefined)
            reflectionMergePartial<ApplyUploadReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyUploadReq): ApplyUploadReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string file_name */ 2:
                    message.fileName = reader.string();
                    break;
                case /* int64 file_size */ 3:
                    message.fileSize = reader.int64().toBigInt();
                    break;
                case /* string mime_type */ 4:
                    message.mimeType = reader.string();
                    break;
                case /* string content_hash */ 5:
                    message.contentHash = reader.string();
                    break;
                case /* chatnow.media.MediaPurpose purpose */ 6:
                    message.purpose = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyUploadReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string file_name = 2; */
        if (message.fileName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileName);
        /* int64 file_size = 3; */
        if (message.fileSize !== 0n)
            writer.tag(3, WireType.Varint).int64(message.fileSize);
        /* string mime_type = 4; */
        if (message.mimeType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.mimeType);
        /* string content_hash = 5; */
        if (message.contentHash !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.contentHash);
        /* chatnow.media.MediaPurpose purpose = 6; */
        if (message.purpose !== 0)
            writer.tag(6, WireType.Varint).int32(message.purpose);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyUploadReq
 */
export const ApplyUploadReq = new ApplyUploadReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyUploadRsp$Type extends MessageType<ApplyUploadRsp> {
    constructor() {
        super("chatnow.media.ApplyUploadRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "already_exists", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "upload_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 6, name: "expires_in_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ApplyUploadRsp>): ApplyUploadRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.alreadyExists = false;
        message.uploadUrl = "";
        message.headers = {};
        message.expiresInSec = 0;
        if (value !== undefined)
            reflectionMergePartial<ApplyUploadRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyUploadRsp): ApplyUploadRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string file_id */ 2:
                    message.fileId = reader.string();
                    break;
                case /* bool already_exists */ 3:
                    message.alreadyExists = reader.bool();
                    break;
                case /* string upload_url */ 4:
                    message.uploadUrl = reader.string();
                    break;
                case /* map<string, string> headers */ 5:
                    this.binaryReadMap5(message.headers, reader, options);
                    break;
                case /* int32 expires_in_sec */ 6:
                    message.expiresInSec = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap5(map: ApplyUploadRsp["headers"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof ApplyUploadRsp["headers"] | undefined, val: ApplyUploadRsp["headers"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for chatnow.media.ApplyUploadRsp.headers");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: ApplyUploadRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string file_id = 2; */
        if (message.fileId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileId);
        /* bool already_exists = 3; */
        if (message.alreadyExists !== false)
            writer.tag(3, WireType.Varint).bool(message.alreadyExists);
        /* string upload_url = 4; */
        if (message.uploadUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.uploadUrl);
        /* map<string, string> headers = 5; */
        for (let k of globalThis.Object.keys(message.headers))
            writer.tag(5, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.headers[k]).join();
        /* int32 expires_in_sec = 6; */
        if (message.expiresInSec !== 0)
            writer.tag(6, WireType.Varint).int32(message.expiresInSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyUploadRsp
 */
export const ApplyUploadRsp = new ApplyUploadRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteUploadReq$Type extends MessageType<CompleteUploadReq> {
    constructor() {
        super("chatnow.media.CompleteUploadReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CompleteUploadReq>): CompleteUploadReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.fileId = "";
        if (value !== undefined)
            reflectionMergePartial<CompleteUploadReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteUploadReq): CompleteUploadReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string file_id */ 2:
                    message.fileId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteUploadReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string file_id = 2; */
        if (message.fileId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.CompleteUploadReq
 */
export const CompleteUploadReq = new CompleteUploadReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteUploadRsp$Type extends MessageType<CompleteUploadRsp> {
    constructor() {
        super("chatnow.media.CompleteUploadRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "file_info", kind: "message", T: () => FileInfo }
        ]);
    }
    create(value?: PartialMessage<CompleteUploadRsp>): CompleteUploadRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CompleteUploadRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteUploadRsp): CompleteUploadRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.media.FileInfo file_info */ 2:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteUploadRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.media.FileInfo file_info = 2; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.CompleteUploadRsp
 */
export const CompleteUploadRsp = new CompleteUploadRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitMultipartReq$Type extends MessageType<InitMultipartReq> {
    constructor() {
        super("chatnow.media.InitMultipartReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "file_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "content_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "purpose", kind: "enum", T: () => ["chatnow.media.MediaPurpose", MediaPurpose] }
        ]);
    }
    create(value?: PartialMessage<InitMultipartReq>): InitMultipartReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.fileName = "";
        message.fileSize = 0n;
        message.mimeType = "";
        message.contentHash = "";
        message.purpose = 0;
        if (value !== undefined)
            reflectionMergePartial<InitMultipartReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitMultipartReq): InitMultipartReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string file_name */ 2:
                    message.fileName = reader.string();
                    break;
                case /* int64 file_size */ 3:
                    message.fileSize = reader.int64().toBigInt();
                    break;
                case /* string mime_type */ 4:
                    message.mimeType = reader.string();
                    break;
                case /* string content_hash */ 5:
                    message.contentHash = reader.string();
                    break;
                case /* chatnow.media.MediaPurpose purpose */ 6:
                    message.purpose = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitMultipartReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string file_name = 2; */
        if (message.fileName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileName);
        /* int64 file_size = 3; */
        if (message.fileSize !== 0n)
            writer.tag(3, WireType.Varint).int64(message.fileSize);
        /* string mime_type = 4; */
        if (message.mimeType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.mimeType);
        /* string content_hash = 5; */
        if (message.contentHash !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.contentHash);
        /* chatnow.media.MediaPurpose purpose = 6; */
        if (message.purpose !== 0)
            writer.tag(6, WireType.Varint).int32(message.purpose);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.InitMultipartReq
 */
export const InitMultipartReq = new InitMultipartReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InitMultipartRsp$Type extends MessageType<InitMultipartRsp> {
    constructor() {
        super("chatnow.media.InitMultipartRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "upload_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "recommended_part_size_bytes", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<InitMultipartRsp>): InitMultipartRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.uploadId = "";
        message.recommendedPartSizeBytes = 0;
        if (value !== undefined)
            reflectionMergePartial<InitMultipartRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InitMultipartRsp): InitMultipartRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string file_id */ 2:
                    message.fileId = reader.string();
                    break;
                case /* string upload_id */ 3:
                    message.uploadId = reader.string();
                    break;
                case /* int32 recommended_part_size_bytes */ 4:
                    message.recommendedPartSizeBytes = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InitMultipartRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string file_id = 2; */
        if (message.fileId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileId);
        /* string upload_id = 3; */
        if (message.uploadId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.uploadId);
        /* int32 recommended_part_size_bytes = 4; */
        if (message.recommendedPartSizeBytes !== 0)
            writer.tag(4, WireType.Varint).int32(message.recommendedPartSizeBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.InitMultipartRsp
 */
export const InitMultipartRsp = new InitMultipartRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyPartReq$Type extends MessageType<ApplyPartReq> {
    constructor() {
        super("chatnow.media.ApplyPartReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "upload_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "part_number", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ApplyPartReq>): ApplyPartReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.uploadId = "";
        message.partNumber = 0;
        if (value !== undefined)
            reflectionMergePartial<ApplyPartReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyPartReq): ApplyPartReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string upload_id */ 2:
                    message.uploadId = reader.string();
                    break;
                case /* int32 part_number */ 3:
                    message.partNumber = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyPartReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string upload_id = 2; */
        if (message.uploadId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uploadId);
        /* int32 part_number = 3; */
        if (message.partNumber !== 0)
            writer.tag(3, WireType.Varint).int32(message.partNumber);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyPartReq
 */
export const ApplyPartReq = new ApplyPartReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyPartRsp$Type extends MessageType<ApplyPartRsp> {
    constructor() {
        super("chatnow.media.ApplyPartRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "upload_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "expires_in_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ApplyPartRsp>): ApplyPartRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.uploadUrl = "";
        message.expiresInSec = 0;
        if (value !== undefined)
            reflectionMergePartial<ApplyPartRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyPartRsp): ApplyPartRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string upload_url */ 2:
                    message.uploadUrl = reader.string();
                    break;
                case /* int32 expires_in_sec */ 3:
                    message.expiresInSec = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyPartRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string upload_url = 2; */
        if (message.uploadUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uploadUrl);
        /* int32 expires_in_sec = 3; */
        if (message.expiresInSec !== 0)
            writer.tag(3, WireType.Varint).int32(message.expiresInSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyPartRsp
 */
export const ApplyPartRsp = new ApplyPartRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PartETag$Type extends MessageType<PartETag> {
    constructor() {
        super("chatnow.media.PartETag", [
            { no: 1, name: "part_number", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "etag", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PartETag>): PartETag {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.partNumber = 0;
        message.etag = "";
        if (value !== undefined)
            reflectionMergePartial<PartETag>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PartETag): PartETag {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 part_number */ 1:
                    message.partNumber = reader.int32();
                    break;
                case /* string etag */ 2:
                    message.etag = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PartETag, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 part_number = 1; */
        if (message.partNumber !== 0)
            writer.tag(1, WireType.Varint).int32(message.partNumber);
        /* string etag = 2; */
        if (message.etag !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.etag);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.PartETag
 */
export const PartETag = new PartETag$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMultipartReq$Type extends MessageType<CompleteMultipartReq> {
    constructor() {
        super("chatnow.media.CompleteMultipartReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "upload_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "parts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PartETag }
        ]);
    }
    create(value?: PartialMessage<CompleteMultipartReq>): CompleteMultipartReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.uploadId = "";
        message.parts = [];
        if (value !== undefined)
            reflectionMergePartial<CompleteMultipartReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteMultipartReq): CompleteMultipartReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string upload_id */ 2:
                    message.uploadId = reader.string();
                    break;
                case /* repeated chatnow.media.PartETag parts */ 3:
                    message.parts.push(PartETag.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteMultipartReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string upload_id = 2; */
        if (message.uploadId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uploadId);
        /* repeated chatnow.media.PartETag parts = 3; */
        for (let i = 0; i < message.parts.length; i++)
            PartETag.internalBinaryWrite(message.parts[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.CompleteMultipartReq
 */
export const CompleteMultipartReq = new CompleteMultipartReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompleteMultipartRsp$Type extends MessageType<CompleteMultipartRsp> {
    constructor() {
        super("chatnow.media.CompleteMultipartRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "file_info", kind: "message", T: () => FileInfo }
        ]);
    }
    create(value?: PartialMessage<CompleteMultipartRsp>): CompleteMultipartRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CompleteMultipartRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CompleteMultipartRsp): CompleteMultipartRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.media.FileInfo file_info */ 2:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CompleteMultipartRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.media.FileInfo file_info = 2; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.CompleteMultipartRsp
 */
export const CompleteMultipartRsp = new CompleteMultipartRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AbortMultipartReq$Type extends MessageType<AbortMultipartReq> {
    constructor() {
        super("chatnow.media.AbortMultipartReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "upload_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AbortMultipartReq>): AbortMultipartReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.uploadId = "";
        if (value !== undefined)
            reflectionMergePartial<AbortMultipartReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AbortMultipartReq): AbortMultipartReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string upload_id */ 2:
                    message.uploadId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AbortMultipartReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string upload_id = 2; */
        if (message.uploadId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.uploadId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.AbortMultipartReq
 */
export const AbortMultipartReq = new AbortMultipartReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AbortMultipartRsp$Type extends MessageType<AbortMultipartRsp> {
    constructor() {
        super("chatnow.media.AbortMultipartRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader }
        ]);
    }
    create(value?: PartialMessage<AbortMultipartRsp>): AbortMultipartRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AbortMultipartRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AbortMultipartRsp): AbortMultipartRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AbortMultipartRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.AbortMultipartRsp
 */
export const AbortMultipartRsp = new AbortMultipartRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyDownloadReq$Type extends MessageType<ApplyDownloadReq> {
    constructor() {
        super("chatnow.media.ApplyDownloadReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ApplyDownloadReq>): ApplyDownloadReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.fileId = "";
        if (value !== undefined)
            reflectionMergePartial<ApplyDownloadReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyDownloadReq): ApplyDownloadReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string file_id */ 2:
                    message.fileId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyDownloadReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string file_id = 2; */
        if (message.fileId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyDownloadReq
 */
export const ApplyDownloadReq = new ApplyDownloadReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyDownloadRsp$Type extends MessageType<ApplyDownloadRsp> {
    constructor() {
        super("chatnow.media.ApplyDownloadRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "download_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "expires_in_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "file_info", kind: "message", T: () => FileInfo }
        ]);
    }
    create(value?: PartialMessage<ApplyDownloadRsp>): ApplyDownloadRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.downloadUrl = "";
        message.expiresInSec = 0;
        if (value !== undefined)
            reflectionMergePartial<ApplyDownloadRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ApplyDownloadRsp): ApplyDownloadRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string download_url */ 2:
                    message.downloadUrl = reader.string();
                    break;
                case /* int32 expires_in_sec */ 3:
                    message.expiresInSec = reader.int32();
                    break;
                case /* chatnow.media.FileInfo file_info */ 4:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ApplyDownloadRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string download_url = 2; */
        if (message.downloadUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.downloadUrl);
        /* int32 expires_in_sec = 3; */
        if (message.expiresInSec !== 0)
            writer.tag(3, WireType.Varint).int32(message.expiresInSec);
        /* chatnow.media.FileInfo file_info = 4; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.ApplyDownloadRsp
 */
export const ApplyDownloadRsp = new ApplyDownloadRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFileInfoReq$Type extends MessageType<GetFileInfoReq> {
    constructor() {
        super("chatnow.media.GetFileInfoReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetFileInfoReq>): GetFileInfoReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.fileId = "";
        if (value !== undefined)
            reflectionMergePartial<GetFileInfoReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFileInfoReq): GetFileInfoReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string file_id */ 2:
                    message.fileId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFileInfoReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string file_id = 2; */
        if (message.fileId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.GetFileInfoReq
 */
export const GetFileInfoReq = new GetFileInfoReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetFileInfoRsp$Type extends MessageType<GetFileInfoRsp> {
    constructor() {
        super("chatnow.media.GetFileInfoRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "file_info", kind: "message", T: () => FileInfo }
        ]);
    }
    create(value?: PartialMessage<GetFileInfoRsp>): GetFileInfoRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetFileInfoRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetFileInfoRsp): GetFileInfoRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.media.FileInfo file_info */ 2:
                    message.fileInfo = FileInfo.internalBinaryRead(reader, reader.uint32(), options, message.fileInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetFileInfoRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.media.FileInfo file_info = 2; */
        if (message.fileInfo)
            FileInfo.internalBinaryWrite(message.fileInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.GetFileInfoRsp
 */
export const GetFileInfoRsp = new GetFileInfoRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SpeechRecognitionReq$Type extends MessageType<SpeechRecognitionReq> {
    constructor() {
        super("chatnow.media.SpeechRecognitionReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "speech_content", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<SpeechRecognitionReq>): SpeechRecognitionReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.speechContent = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<SpeechRecognitionReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SpeechRecognitionReq): SpeechRecognitionReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* bytes speech_content */ 2:
                    message.speechContent = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SpeechRecognitionReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* bytes speech_content = 2; */
        if (message.speechContent.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.speechContent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.SpeechRecognitionReq
 */
export const SpeechRecognitionReq = new SpeechRecognitionReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SpeechRecognitionRsp$Type extends MessageType<SpeechRecognitionRsp> {
    constructor() {
        super("chatnow.media.SpeechRecognitionRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "recognition_result", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SpeechRecognitionRsp>): SpeechRecognitionRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.recognitionResult = "";
        if (value !== undefined)
            reflectionMergePartial<SpeechRecognitionRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SpeechRecognitionRsp): SpeechRecognitionRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string recognition_result */ 2:
                    message.recognitionResult = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SpeechRecognitionRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string recognition_result = 2; */
        if (message.recognitionResult !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.recognitionResult);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.media.SpeechRecognitionRsp
 */
export const SpeechRecognitionRsp = new SpeechRecognitionRsp$Type();
/**
 * @generated ServiceType for protobuf service chatnow.media.MediaService
 */
export const MediaService = new ServiceType("chatnow.media.MediaService", [
    { name: "ApplyUpload", options: {}, I: ApplyUploadReq, O: ApplyUploadRsp },
    { name: "CompleteUpload", options: {}, I: CompleteUploadReq, O: CompleteUploadRsp },
    { name: "InitMultipartUpload", options: {}, I: InitMultipartReq, O: InitMultipartRsp },
    { name: "ApplyPartUpload", options: {}, I: ApplyPartReq, O: ApplyPartRsp },
    { name: "CompleteMultipartUpload", options: {}, I: CompleteMultipartReq, O: CompleteMultipartRsp },
    { name: "AbortMultipartUpload", options: {}, I: AbortMultipartReq, O: AbortMultipartRsp },
    { name: "ApplyDownload", options: {}, I: ApplyDownloadReq, O: ApplyDownloadRsp },
    { name: "GetFileInfo", options: {}, I: GetFileInfoReq, O: GetFileInfoRsp },
    { name: "SpeechRecognition", options: {}, I: SpeechRecognitionReq, O: SpeechRecognitionRsp }
]);
