// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "push/notify.proto" (package "chatnow.push", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Message } from "../message/message_types";
import { UserInfo } from "../common/types";
/**
 * @generated from protobuf message chatnow.push.NotifyClientAuth
 */
export interface NotifyClientAuth {
    /**
     * @generated from protobuf field: string access_token = 1
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string device_id = 2
     */
    deviceId: string;
    /**
     * @generated from protobuf field: optional uint64 last_user_seq = 3
     */
    lastUserSeq?: bigint;
}
/**
 * @generated from protobuf message chatnow.push.NotifyMsgPushAck
 */
export interface NotifyMsgPushAck {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string device_id = 2
     */
    deviceId: string;
    /**
     * @generated from protobuf field: int64 message_id = 3
     */
    messageId: bigint;
    /**
     * @generated from protobuf field: uint64 user_seq = 4
     */
    userSeq: bigint;
    /**
     * @generated from protobuf field: string conversation_id = 5
     */
    conversationId: string;
}
/**
 * @generated from protobuf message chatnow.push.NotifyHeartbeat
 */
export interface NotifyHeartbeat {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: uint64 last_user_seq = 2
     */
    lastUserSeq: bigint;
}
/**
 * @generated from protobuf message chatnow.push.NotifyFriendAddApply
 */
export interface NotifyFriendAddApply {
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 1
     */
    userInfo?: UserInfo;
}
/**
 * @generated from protobuf message chatnow.push.NotifyFriendAddProcess
 */
export interface NotifyFriendAddProcess {
    /**
     * @generated from protobuf field: bool agree = 1
     */
    agree: boolean;
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 2
     */
    userInfo?: UserInfo;
}
/**
 * @generated from protobuf message chatnow.push.NotifyFriendRemove
 */
export interface NotifyFriendRemove {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
}
/**
 * @generated from protobuf message chatnow.push.NotifyNewConversation
 */
export interface NotifyNewConversation {
    /**
     * @generated from protobuf field: bytes conversation_payload = 1
     */
    conversationPayload: Uint8Array;
}
/**
 * @generated from protobuf message chatnow.push.NotifyNewMessage
 */
export interface NotifyNewMessage {
    /**
     * @generated from protobuf field: chatnow.message.Message message_info = 1
     */
    messageInfo?: Message;
}
/**
 * @generated from protobuf message chatnow.push.NotifyMessageRecalled
 */
export interface NotifyMessageRecalled {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: int64 message_id = 2
     */
    messageId: bigint;
}
/**
 * @generated from protobuf message chatnow.push.NotifyPresenceChange
 */
export interface NotifyPresenceChange {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string state = 2
     */
    state: string;
}
/**
 * @generated from protobuf message chatnow.push.NotifyTyping
 */
export interface NotifyTyping {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string conversation_id = 2
     */
    conversationId: string;
    /**
     * @generated from protobuf field: bool is_typing = 3
     */
    isTyping: boolean;
}
/**
 * @generated from protobuf message chatnow.push.NotifyReactionChanged
 */
export interface NotifyReactionChanged {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: int64 message_id = 2
     */
    messageId: bigint;
    /**
     * @generated from protobuf field: string actor_user_id = 3
     */
    actorUserId: string;
    /**
     * @generated from protobuf field: string emoji = 4
     */
    emoji: string;
    /**
     * @generated from protobuf field: bool added = 5
     */
    added: boolean;
}
/**
 * @generated from protobuf message chatnow.push.NotifyPinChanged
 */
export interface NotifyPinChanged {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: int64 message_id = 2
     */
    messageId: bigint;
    /**
     * @generated from protobuf field: string actor_user_id = 3
     */
    actorUserId: string;
    /**
     * @generated from protobuf field: bool is_pinned = 4
     */
    isPinned: boolean;
}
/**
 * @generated from protobuf message chatnow.push.NotifyReadReceipt
 */
export interface NotifyReadReceipt {
    /**
     * @generated from protobuf field: string conversation_id = 1
     */
    conversationId: string;
    /**
     * @generated from protobuf field: string reader_user_id = 2
     */
    readerUserId: string;
    /**
     * @generated from protobuf field: uint64 last_read_seq = 3
     */
    lastReadSeq: bigint;
}
/**
 * @generated from protobuf message chatnow.push.NotifyKicked
 */
export interface NotifyKicked {
    /**
     * @generated from protobuf field: chatnow.push.NotifyType reason = 1
     */
    reason: NotifyType;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message chatnow.push.NotifyMessage
 */
export interface NotifyMessage {
    /**
     * @generated from protobuf field: optional string notify_event_id = 1
     */
    notifyEventId?: string;
    /**
     * @generated from protobuf field: chatnow.push.NotifyType notify_type = 2
     */
    notifyType: NotifyType;
    /**
     * @generated from protobuf field: optional string trace_id = 14
     */
    traceId?: string;
    /**
     * @generated from protobuf oneof: notify_remarks
     */
    notifyRemarks: {
        oneofKind: "friendAddApply";
        /**
         * @generated from protobuf field: chatnow.push.NotifyFriendAddApply friend_add_apply = 3
         */
        friendAddApply: NotifyFriendAddApply;
    } | {
        oneofKind: "friendProcessResult";
        /**
         * @generated from protobuf field: chatnow.push.NotifyFriendAddProcess friend_process_result = 4
         */
        friendProcessResult: NotifyFriendAddProcess;
    } | {
        oneofKind: "friendRemove";
        /**
         * @generated from protobuf field: chatnow.push.NotifyFriendRemove friend_remove = 7
         */
        friendRemove: NotifyFriendRemove;
    } | {
        oneofKind: "newConversationInfo";
        /**
         * @generated from protobuf field: chatnow.push.NotifyNewConversation new_conversation_info = 5
         */
        newConversationInfo: NotifyNewConversation;
    } | {
        oneofKind: "newMessageInfo";
        /**
         * @generated from protobuf field: chatnow.push.NotifyNewMessage new_message_info = 6
         */
        newMessageInfo: NotifyNewMessage;
    } | {
        oneofKind: "msgPushAck";
        /**
         * @generated from protobuf field: chatnow.push.NotifyMsgPushAck msg_push_ack = 8
         */
        msgPushAck: NotifyMsgPushAck;
    } | {
        oneofKind: "heartbeat";
        /**
         * @generated from protobuf field: chatnow.push.NotifyHeartbeat heartbeat = 9
         */
        heartbeat: NotifyHeartbeat;
    } | {
        oneofKind: "clientAuth";
        /**
         * @generated from protobuf field: chatnow.push.NotifyClientAuth client_auth = 10
         */
        clientAuth: NotifyClientAuth;
    } | {
        oneofKind: "messageRecalled";
        /**
         * @generated from protobuf field: chatnow.push.NotifyMessageRecalled message_recalled = 11
         */
        messageRecalled: NotifyMessageRecalled;
    } | {
        oneofKind: "presenceChange";
        /**
         * @generated from protobuf field: chatnow.push.NotifyPresenceChange presence_change = 12
         */
        presenceChange: NotifyPresenceChange;
    } | {
        oneofKind: "typing";
        /**
         * @generated from protobuf field: chatnow.push.NotifyTyping typing = 13
         */
        typing: NotifyTyping;
    } | {
        oneofKind: "reactionChanged";
        /**
         * @generated from protobuf field: chatnow.push.NotifyReactionChanged reaction_changed = 15
         */
        reactionChanged: NotifyReactionChanged;
    } | {
        oneofKind: "pinChanged";
        /**
         * @generated from protobuf field: chatnow.push.NotifyPinChanged pin_changed = 16
         */
        pinChanged: NotifyPinChanged;
    } | {
        oneofKind: "readReceipt";
        /**
         * @generated from protobuf field: chatnow.push.NotifyReadReceipt read_receipt = 17
         */
        readReceipt: NotifyReadReceipt;
    } | {
        oneofKind: "kicked";
        /**
         * @generated from protobuf field: chatnow.push.NotifyKicked kicked = 18
         */
        kicked: NotifyKicked;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf enum chatnow.push.NotifyType
 */
export enum NotifyType {
    /**
     * @generated from protobuf enum value: FRIEND_ADD_APPLY_NOTIFY = 0;
     */
    FRIEND_ADD_APPLY_NOTIFY = 0,
    /**
     * @generated from protobuf enum value: FRIEND_ADD_PROCESS_NOTIFY = 1;
     */
    FRIEND_ADD_PROCESS_NOTIFY = 1,
    /**
     * @generated from protobuf enum value: CONVERSATION_CREATE_NOTIFY = 2;
     */
    CONVERSATION_CREATE_NOTIFY = 2,
    /**
     * @generated from protobuf enum value: CHAT_MESSAGE_NOTIFY = 3;
     */
    CHAT_MESSAGE_NOTIFY = 3,
    /**
     * @generated from protobuf enum value: FRIEND_REMOVE_NOTIFY = 4;
     */
    FRIEND_REMOVE_NOTIFY = 4,
    /**
     * @generated from protobuf enum value: MESSAGE_RECALLED_NOTIFY = 5;
     */
    MESSAGE_RECALLED_NOTIFY = 5,
    /**
     * @generated from protobuf enum value: PRESENCE_CHANGE_NOTIFY = 6;
     */
    PRESENCE_CHANGE_NOTIFY = 6,
    /**
     * @generated from protobuf enum value: TYPING_NOTIFY = 7;
     */
    TYPING_NOTIFY = 7,
    /**
     * @generated from protobuf enum value: REACTION_CHANGED_NOTIFY = 8;
     */
    REACTION_CHANGED_NOTIFY = 8,
    /**
     * @generated from protobuf enum value: PIN_CHANGED_NOTIFY = 9;
     */
    PIN_CHANGED_NOTIFY = 9,
    /**
     * @generated from protobuf enum value: READ_RECEIPT_NOTIFY = 10;
     */
    READ_RECEIPT_NOTIFY = 10,
    /**
     * @generated from protobuf enum value: KICKED_BY_NEW_DEVICE = 11;
     */
    KICKED_BY_NEW_DEVICE = 11,
    /**
     * @generated from protobuf enum value: KICKED_BY_REVOKE = 12;
     */
    KICKED_BY_REVOKE = 12,
    /**
     * @generated from protobuf enum value: FORCE_LOGOUT = 13;
     */
    FORCE_LOGOUT = 13,
    /**
     * @generated from protobuf enum value: CONVERSATION_DISMISSED_NOTIFY = 14;
     */
    CONVERSATION_DISMISSED_NOTIFY = 14,
    /**
     * @generated from protobuf enum value: CLIENT_AUTH = 49;
     */
    CLIENT_AUTH = 49,
    /**
     * @generated from protobuf enum value: MSG_PUSH_ACK = 50;
     */
    MSG_PUSH_ACK = 50,
    /**
     * @generated from protobuf enum value: CLIENT_HEARTBEAT = 51;
     */
    CLIENT_HEARTBEAT = 51
}
// @generated message type with reflection information, may provide speed optimized methods
class NotifyClientAuth$Type extends MessageType<NotifyClientAuth> {
    constructor() {
        super("chatnow.push.NotifyClientAuth", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "last_user_seq", kind: "scalar", opt: true, T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyClientAuth>): NotifyClientAuth {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accessToken = "";
        message.deviceId = "";
        if (value !== undefined)
            reflectionMergePartial<NotifyClientAuth>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyClientAuth): NotifyClientAuth {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string access_token */ 1:
                    message.accessToken = reader.string();
                    break;
                case /* string device_id */ 2:
                    message.deviceId = reader.string();
                    break;
                case /* optional uint64 last_user_seq */ 3:
                    message.lastUserSeq = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyClientAuth, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string access_token = 1; */
        if (message.accessToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.accessToken);
        /* string device_id = 2; */
        if (message.deviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.deviceId);
        /* optional uint64 last_user_seq = 3; */
        if (message.lastUserSeq !== undefined)
            writer.tag(3, WireType.Varint).uint64(message.lastUserSeq);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyClientAuth
 */
export const NotifyClientAuth = new NotifyClientAuth$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyMsgPushAck$Type extends MessageType<NotifyMsgPushAck> {
    constructor() {
        super("chatnow.push.NotifyMsgPushAck", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "user_seq", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyMsgPushAck>): NotifyMsgPushAck {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.deviceId = "";
        message.messageId = 0n;
        message.userSeq = 0n;
        message.conversationId = "";
        if (value !== undefined)
            reflectionMergePartial<NotifyMsgPushAck>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyMsgPushAck): NotifyMsgPushAck {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string device_id */ 2:
                    message.deviceId = reader.string();
                    break;
                case /* int64 message_id */ 3:
                    message.messageId = reader.int64().toBigInt();
                    break;
                case /* uint64 user_seq */ 4:
                    message.userSeq = reader.uint64().toBigInt();
                    break;
                case /* string conversation_id */ 5:
                    message.conversationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyMsgPushAck, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string device_id = 2; */
        if (message.deviceId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.deviceId);
        /* int64 message_id = 3; */
        if (message.messageId !== 0n)
            writer.tag(3, WireType.Varint).int64(message.messageId);
        /* uint64 user_seq = 4; */
        if (message.userSeq !== 0n)
            writer.tag(4, WireType.Varint).uint64(message.userSeq);
        /* string conversation_id = 5; */
        if (message.conversationId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.conversationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyMsgPushAck
 */
export const NotifyMsgPushAck = new NotifyMsgPushAck$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyHeartbeat$Type extends MessageType<NotifyHeartbeat> {
    constructor() {
        super("chatnow.push.NotifyHeartbeat", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "last_user_seq", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyHeartbeat>): NotifyHeartbeat {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.lastUserSeq = 0n;
        if (value !== undefined)
            reflectionMergePartial<NotifyHeartbeat>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyHeartbeat): NotifyHeartbeat {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* uint64 last_user_seq */ 2:
                    message.lastUserSeq = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyHeartbeat, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* uint64 last_user_seq = 2; */
        if (message.lastUserSeq !== 0n)
            writer.tag(2, WireType.Varint).uint64(message.lastUserSeq);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyHeartbeat
 */
export const NotifyHeartbeat = new NotifyHeartbeat$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyFriendAddApply$Type extends MessageType<NotifyFriendAddApply> {
    constructor() {
        super("chatnow.push.NotifyFriendAddApply", [
            { no: 1, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<NotifyFriendAddApply>): NotifyFriendAddApply {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<NotifyFriendAddApply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyFriendAddApply): NotifyFriendAddApply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.UserInfo user_info */ 1:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyFriendAddApply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.UserInfo user_info = 1; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyFriendAddApply
 */
export const NotifyFriendAddApply = new NotifyFriendAddApply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyFriendAddProcess$Type extends MessageType<NotifyFriendAddProcess> {
    constructor() {
        super("chatnow.push.NotifyFriendAddProcess", [
            { no: 1, name: "agree", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<NotifyFriendAddProcess>): NotifyFriendAddProcess {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agree = false;
        if (value !== undefined)
            reflectionMergePartial<NotifyFriendAddProcess>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyFriendAddProcess): NotifyFriendAddProcess {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool agree */ 1:
                    message.agree = reader.bool();
                    break;
                case /* chatnow.common.UserInfo user_info */ 2:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyFriendAddProcess, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool agree = 1; */
        if (message.agree !== false)
            writer.tag(1, WireType.Varint).bool(message.agree);
        /* chatnow.common.UserInfo user_info = 2; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyFriendAddProcess
 */
export const NotifyFriendAddProcess = new NotifyFriendAddProcess$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyFriendRemove$Type extends MessageType<NotifyFriendRemove> {
    constructor() {
        super("chatnow.push.NotifyFriendRemove", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyFriendRemove>): NotifyFriendRemove {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<NotifyFriendRemove>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyFriendRemove): NotifyFriendRemove {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyFriendRemove, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyFriendRemove
 */
export const NotifyFriendRemove = new NotifyFriendRemove$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyNewConversation$Type extends MessageType<NotifyNewConversation> {
    constructor() {
        super("chatnow.push.NotifyNewConversation", [
            { no: 1, name: "conversation_payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyNewConversation>): NotifyNewConversation {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationPayload = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<NotifyNewConversation>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyNewConversation): NotifyNewConversation {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes conversation_payload */ 1:
                    message.conversationPayload = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyNewConversation, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes conversation_payload = 1; */
        if (message.conversationPayload.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.conversationPayload);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyNewConversation
 */
export const NotifyNewConversation = new NotifyNewConversation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyNewMessage$Type extends MessageType<NotifyNewMessage> {
    constructor() {
        super("chatnow.push.NotifyNewMessage", [
            { no: 1, name: "message_info", kind: "message", T: () => Message }
        ]);
    }
    create(value?: PartialMessage<NotifyNewMessage>): NotifyNewMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<NotifyNewMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyNewMessage): NotifyNewMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.message.Message message_info */ 1:
                    message.messageInfo = Message.internalBinaryRead(reader, reader.uint32(), options, message.messageInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyNewMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.message.Message message_info = 1; */
        if (message.messageInfo)
            Message.internalBinaryWrite(message.messageInfo, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyNewMessage
 */
export const NotifyNewMessage = new NotifyNewMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyMessageRecalled$Type extends MessageType<NotifyMessageRecalled> {
    constructor() {
        super("chatnow.push.NotifyMessageRecalled", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyMessageRecalled>): NotifyMessageRecalled {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.messageId = 0n;
        if (value !== undefined)
            reflectionMergePartial<NotifyMessageRecalled>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyMessageRecalled): NotifyMessageRecalled {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* int64 message_id */ 2:
                    message.messageId = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyMessageRecalled, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* int64 message_id = 2; */
        if (message.messageId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.messageId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyMessageRecalled
 */
export const NotifyMessageRecalled = new NotifyMessageRecalled$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyPresenceChange$Type extends MessageType<NotifyPresenceChange> {
    constructor() {
        super("chatnow.push.NotifyPresenceChange", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyPresenceChange>): NotifyPresenceChange {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.state = "";
        if (value !== undefined)
            reflectionMergePartial<NotifyPresenceChange>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyPresenceChange): NotifyPresenceChange {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string state */ 2:
                    message.state = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyPresenceChange, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string state = 2; */
        if (message.state !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.state);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyPresenceChange
 */
export const NotifyPresenceChange = new NotifyPresenceChange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyTyping$Type extends MessageType<NotifyTyping> {
    constructor() {
        super("chatnow.push.NotifyTyping", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "is_typing", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyTyping>): NotifyTyping {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.conversationId = "";
        message.isTyping = false;
        if (value !== undefined)
            reflectionMergePartial<NotifyTyping>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyTyping): NotifyTyping {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string conversation_id */ 2:
                    message.conversationId = reader.string();
                    break;
                case /* bool is_typing */ 3:
                    message.isTyping = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyTyping, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string conversation_id = 2; */
        if (message.conversationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationId);
        /* bool is_typing = 3; */
        if (message.isTyping !== false)
            writer.tag(3, WireType.Varint).bool(message.isTyping);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyTyping
 */
export const NotifyTyping = new NotifyTyping$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyReactionChanged$Type extends MessageType<NotifyReactionChanged> {
    constructor() {
        super("chatnow.push.NotifyReactionChanged", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "actor_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "emoji", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "added", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyReactionChanged>): NotifyReactionChanged {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.messageId = 0n;
        message.actorUserId = "";
        message.emoji = "";
        message.added = false;
        if (value !== undefined)
            reflectionMergePartial<NotifyReactionChanged>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyReactionChanged): NotifyReactionChanged {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* int64 message_id */ 2:
                    message.messageId = reader.int64().toBigInt();
                    break;
                case /* string actor_user_id */ 3:
                    message.actorUserId = reader.string();
                    break;
                case /* string emoji */ 4:
                    message.emoji = reader.string();
                    break;
                case /* bool added */ 5:
                    message.added = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyReactionChanged, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* int64 message_id = 2; */
        if (message.messageId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.messageId);
        /* string actor_user_id = 3; */
        if (message.actorUserId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.actorUserId);
        /* string emoji = 4; */
        if (message.emoji !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.emoji);
        /* bool added = 5; */
        if (message.added !== false)
            writer.tag(5, WireType.Varint).bool(message.added);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyReactionChanged
 */
export const NotifyReactionChanged = new NotifyReactionChanged$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyPinChanged$Type extends MessageType<NotifyPinChanged> {
    constructor() {
        super("chatnow.push.NotifyPinChanged", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "actor_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "is_pinned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyPinChanged>): NotifyPinChanged {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.messageId = 0n;
        message.actorUserId = "";
        message.isPinned = false;
        if (value !== undefined)
            reflectionMergePartial<NotifyPinChanged>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyPinChanged): NotifyPinChanged {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* int64 message_id */ 2:
                    message.messageId = reader.int64().toBigInt();
                    break;
                case /* string actor_user_id */ 3:
                    message.actorUserId = reader.string();
                    break;
                case /* bool is_pinned */ 4:
                    message.isPinned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyPinChanged, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* int64 message_id = 2; */
        if (message.messageId !== 0n)
            writer.tag(2, WireType.Varint).int64(message.messageId);
        /* string actor_user_id = 3; */
        if (message.actorUserId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.actorUserId);
        /* bool is_pinned = 4; */
        if (message.isPinned !== false)
            writer.tag(4, WireType.Varint).bool(message.isPinned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyPinChanged
 */
export const NotifyPinChanged = new NotifyPinChanged$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyReadReceipt$Type extends MessageType<NotifyReadReceipt> {
    constructor() {
        super("chatnow.push.NotifyReadReceipt", [
            { no: 1, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reader_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "last_read_seq", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyReadReceipt>): NotifyReadReceipt {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.conversationId = "";
        message.readerUserId = "";
        message.lastReadSeq = 0n;
        if (value !== undefined)
            reflectionMergePartial<NotifyReadReceipt>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyReadReceipt): NotifyReadReceipt {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string conversation_id */ 1:
                    message.conversationId = reader.string();
                    break;
                case /* string reader_user_id */ 2:
                    message.readerUserId = reader.string();
                    break;
                case /* uint64 last_read_seq */ 3:
                    message.lastReadSeq = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyReadReceipt, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string conversation_id = 1; */
        if (message.conversationId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.conversationId);
        /* string reader_user_id = 2; */
        if (message.readerUserId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.readerUserId);
        /* uint64 last_read_seq = 3; */
        if (message.lastReadSeq !== 0n)
            writer.tag(3, WireType.Varint).uint64(message.lastReadSeq);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyReadReceipt
 */
export const NotifyReadReceipt = new NotifyReadReceipt$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyKicked$Type extends MessageType<NotifyKicked> {
    constructor() {
        super("chatnow.push.NotifyKicked", [
            { no: 1, name: "reason", kind: "enum", T: () => ["chatnow.push.NotifyType", NotifyType] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<NotifyKicked>): NotifyKicked {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reason = 0;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<NotifyKicked>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyKicked): NotifyKicked {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.push.NotifyType reason */ 1:
                    message.reason = reader.int32();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyKicked, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.push.NotifyType reason = 1; */
        if (message.reason !== 0)
            writer.tag(1, WireType.Varint).int32(message.reason);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyKicked
 */
export const NotifyKicked = new NotifyKicked$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NotifyMessage$Type extends MessageType<NotifyMessage> {
    constructor() {
        super("chatnow.push.NotifyMessage", [
            { no: 1, name: "notify_event_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "notify_type", kind: "enum", T: () => ["chatnow.push.NotifyType", NotifyType] },
            { no: 14, name: "trace_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "friend_add_apply", kind: "message", oneof: "notifyRemarks", T: () => NotifyFriendAddApply },
            { no: 4, name: "friend_process_result", kind: "message", oneof: "notifyRemarks", T: () => NotifyFriendAddProcess },
            { no: 7, name: "friend_remove", kind: "message", oneof: "notifyRemarks", T: () => NotifyFriendRemove },
            { no: 5, name: "new_conversation_info", kind: "message", oneof: "notifyRemarks", T: () => NotifyNewConversation },
            { no: 6, name: "new_message_info", kind: "message", oneof: "notifyRemarks", T: () => NotifyNewMessage },
            { no: 8, name: "msg_push_ack", kind: "message", oneof: "notifyRemarks", T: () => NotifyMsgPushAck },
            { no: 9, name: "heartbeat", kind: "message", oneof: "notifyRemarks", T: () => NotifyHeartbeat },
            { no: 10, name: "client_auth", kind: "message", oneof: "notifyRemarks", T: () => NotifyClientAuth },
            { no: 11, name: "message_recalled", kind: "message", oneof: "notifyRemarks", T: () => NotifyMessageRecalled },
            { no: 12, name: "presence_change", kind: "message", oneof: "notifyRemarks", T: () => NotifyPresenceChange },
            { no: 13, name: "typing", kind: "message", oneof: "notifyRemarks", T: () => NotifyTyping },
            { no: 15, name: "reaction_changed", kind: "message", oneof: "notifyRemarks", T: () => NotifyReactionChanged },
            { no: 16, name: "pin_changed", kind: "message", oneof: "notifyRemarks", T: () => NotifyPinChanged },
            { no: 17, name: "read_receipt", kind: "message", oneof: "notifyRemarks", T: () => NotifyReadReceipt },
            { no: 18, name: "kicked", kind: "message", oneof: "notifyRemarks", T: () => NotifyKicked }
        ]);
    }
    create(value?: PartialMessage<NotifyMessage>): NotifyMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.notifyType = 0;
        message.notifyRemarks = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<NotifyMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NotifyMessage): NotifyMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string notify_event_id */ 1:
                    message.notifyEventId = reader.string();
                    break;
                case /* chatnow.push.NotifyType notify_type */ 2:
                    message.notifyType = reader.int32();
                    break;
                case /* optional string trace_id */ 14:
                    message.traceId = reader.string();
                    break;
                case /* chatnow.push.NotifyFriendAddApply friend_add_apply */ 3:
                    message.notifyRemarks = {
                        oneofKind: "friendAddApply",
                        friendAddApply: NotifyFriendAddApply.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).friendAddApply)
                    };
                    break;
                case /* chatnow.push.NotifyFriendAddProcess friend_process_result */ 4:
                    message.notifyRemarks = {
                        oneofKind: "friendProcessResult",
                        friendProcessResult: NotifyFriendAddProcess.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).friendProcessResult)
                    };
                    break;
                case /* chatnow.push.NotifyFriendRemove friend_remove */ 7:
                    message.notifyRemarks = {
                        oneofKind: "friendRemove",
                        friendRemove: NotifyFriendRemove.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).friendRemove)
                    };
                    break;
                case /* chatnow.push.NotifyNewConversation new_conversation_info */ 5:
                    message.notifyRemarks = {
                        oneofKind: "newConversationInfo",
                        newConversationInfo: NotifyNewConversation.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).newConversationInfo)
                    };
                    break;
                case /* chatnow.push.NotifyNewMessage new_message_info */ 6:
                    message.notifyRemarks = {
                        oneofKind: "newMessageInfo",
                        newMessageInfo: NotifyNewMessage.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).newMessageInfo)
                    };
                    break;
                case /* chatnow.push.NotifyMsgPushAck msg_push_ack */ 8:
                    message.notifyRemarks = {
                        oneofKind: "msgPushAck",
                        msgPushAck: NotifyMsgPushAck.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).msgPushAck)
                    };
                    break;
                case /* chatnow.push.NotifyHeartbeat heartbeat */ 9:
                    message.notifyRemarks = {
                        oneofKind: "heartbeat",
                        heartbeat: NotifyHeartbeat.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).heartbeat)
                    };
                    break;
                case /* chatnow.push.NotifyClientAuth client_auth */ 10:
                    message.notifyRemarks = {
                        oneofKind: "clientAuth",
                        clientAuth: NotifyClientAuth.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).clientAuth)
                    };
                    break;
                case /* chatnow.push.NotifyMessageRecalled message_recalled */ 11:
                    message.notifyRemarks = {
                        oneofKind: "messageRecalled",
                        messageRecalled: NotifyMessageRecalled.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).messageRecalled)
                    };
                    break;
                case /* chatnow.push.NotifyPresenceChange presence_change */ 12:
                    message.notifyRemarks = {
                        oneofKind: "presenceChange",
                        presenceChange: NotifyPresenceChange.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).presenceChange)
                    };
                    break;
                case /* chatnow.push.NotifyTyping typing */ 13:
                    message.notifyRemarks = {
                        oneofKind: "typing",
                        typing: NotifyTyping.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).typing)
                    };
                    break;
                case /* chatnow.push.NotifyReactionChanged reaction_changed */ 15:
                    message.notifyRemarks = {
                        oneofKind: "reactionChanged",
                        reactionChanged: NotifyReactionChanged.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).reactionChanged)
                    };
                    break;
                case /* chatnow.push.NotifyPinChanged pin_changed */ 16:
                    message.notifyRemarks = {
                        oneofKind: "pinChanged",
                        pinChanged: NotifyPinChanged.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).pinChanged)
                    };
                    break;
                case /* chatnow.push.NotifyReadReceipt read_receipt */ 17:
                    message.notifyRemarks = {
                        oneofKind: "readReceipt",
                        readReceipt: NotifyReadReceipt.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).readReceipt)
                    };
                    break;
                case /* chatnow.push.NotifyKicked kicked */ 18:
                    message.notifyRemarks = {
                        oneofKind: "kicked",
                        kicked: NotifyKicked.internalBinaryRead(reader, reader.uint32(), options, (message.notifyRemarks as any).kicked)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NotifyMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string notify_event_id = 1; */
        if (message.notifyEventId !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.notifyEventId);
        /* chatnow.push.NotifyType notify_type = 2; */
        if (message.notifyType !== 0)
            writer.tag(2, WireType.Varint).int32(message.notifyType);
        /* chatnow.push.NotifyFriendAddApply friend_add_apply = 3; */
        if (message.notifyRemarks.oneofKind === "friendAddApply")
            NotifyFriendAddApply.internalBinaryWrite(message.notifyRemarks.friendAddApply, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyFriendAddProcess friend_process_result = 4; */
        if (message.notifyRemarks.oneofKind === "friendProcessResult")
            NotifyFriendAddProcess.internalBinaryWrite(message.notifyRemarks.friendProcessResult, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyNewConversation new_conversation_info = 5; */
        if (message.notifyRemarks.oneofKind === "newConversationInfo")
            NotifyNewConversation.internalBinaryWrite(message.notifyRemarks.newConversationInfo, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyNewMessage new_message_info = 6; */
        if (message.notifyRemarks.oneofKind === "newMessageInfo")
            NotifyNewMessage.internalBinaryWrite(message.notifyRemarks.newMessageInfo, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyFriendRemove friend_remove = 7; */
        if (message.notifyRemarks.oneofKind === "friendRemove")
            NotifyFriendRemove.internalBinaryWrite(message.notifyRemarks.friendRemove, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyMsgPushAck msg_push_ack = 8; */
        if (message.notifyRemarks.oneofKind === "msgPushAck")
            NotifyMsgPushAck.internalBinaryWrite(message.notifyRemarks.msgPushAck, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyHeartbeat heartbeat = 9; */
        if (message.notifyRemarks.oneofKind === "heartbeat")
            NotifyHeartbeat.internalBinaryWrite(message.notifyRemarks.heartbeat, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyClientAuth client_auth = 10; */
        if (message.notifyRemarks.oneofKind === "clientAuth")
            NotifyClientAuth.internalBinaryWrite(message.notifyRemarks.clientAuth, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyMessageRecalled message_recalled = 11; */
        if (message.notifyRemarks.oneofKind === "messageRecalled")
            NotifyMessageRecalled.internalBinaryWrite(message.notifyRemarks.messageRecalled, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyPresenceChange presence_change = 12; */
        if (message.notifyRemarks.oneofKind === "presenceChange")
            NotifyPresenceChange.internalBinaryWrite(message.notifyRemarks.presenceChange, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyTyping typing = 13; */
        if (message.notifyRemarks.oneofKind === "typing")
            NotifyTyping.internalBinaryWrite(message.notifyRemarks.typing, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* optional string trace_id = 14; */
        if (message.traceId !== undefined)
            writer.tag(14, WireType.LengthDelimited).string(message.traceId);
        /* chatnow.push.NotifyReactionChanged reaction_changed = 15; */
        if (message.notifyRemarks.oneofKind === "reactionChanged")
            NotifyReactionChanged.internalBinaryWrite(message.notifyRemarks.reactionChanged, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyPinChanged pin_changed = 16; */
        if (message.notifyRemarks.oneofKind === "pinChanged")
            NotifyPinChanged.internalBinaryWrite(message.notifyRemarks.pinChanged, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyReadReceipt read_receipt = 17; */
        if (message.notifyRemarks.oneofKind === "readReceipt")
            NotifyReadReceipt.internalBinaryWrite(message.notifyRemarks.readReceipt, writer.tag(17, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.push.NotifyKicked kicked = 18; */
        if (message.notifyRemarks.oneofKind === "kicked")
            NotifyKicked.internalBinaryWrite(message.notifyRemarks.kicked, writer.tag(18, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.push.NotifyMessage
 */
export const NotifyMessage = new NotifyMessage$Type();
