// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "presence/presence_service.proto" (package "chatnow.presence", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PresenceService } from "./presence_service";
import type { TypingRsp } from "./presence_service";
import type { TypingReq } from "./presence_service";
import type { UnsubscribeRsp } from "./presence_service";
import type { UnsubscribeReq } from "./presence_service";
import type { SubscribeRsp } from "./presence_service";
import type { SubscribeReq } from "./presence_service";
import type { BatchGetPresenceRsp } from "./presence_service";
import type { BatchGetPresenceReq } from "./presence_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetPresenceRsp } from "./presence_service";
import type { GetPresenceReq } from "./presence_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.presence.PresenceService
 */
export interface IPresenceServiceClient {
    /**
     * @generated from protobuf rpc: GetPresence
     */
    getPresence(input: GetPresenceReq, options?: RpcOptions): UnaryCall<GetPresenceReq, GetPresenceRsp>;
    /**
     * @generated from protobuf rpc: BatchGetPresence
     */
    batchGetPresence(input: BatchGetPresenceReq, options?: RpcOptions): UnaryCall<BatchGetPresenceReq, BatchGetPresenceRsp>;
    /**
     * @generated from protobuf rpc: SubscribePresence
     */
    subscribePresence(input: SubscribeReq, options?: RpcOptions): UnaryCall<SubscribeReq, SubscribeRsp>;
    /**
     * @generated from protobuf rpc: UnsubscribePresence
     */
    unsubscribePresence(input: UnsubscribeReq, options?: RpcOptions): UnaryCall<UnsubscribeReq, UnsubscribeRsp>;
    /**
     * @generated from protobuf rpc: SendTyping
     */
    sendTyping(input: TypingReq, options?: RpcOptions): UnaryCall<TypingReq, TypingRsp>;
}
/**
 * @generated from protobuf service chatnow.presence.PresenceService
 */
export class PresenceServiceClient implements IPresenceServiceClient, ServiceInfo {
    typeName = PresenceService.typeName;
    methods = PresenceService.methods;
    options = PresenceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPresence
     */
    getPresence(input: GetPresenceReq, options?: RpcOptions): UnaryCall<GetPresenceReq, GetPresenceRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPresenceReq, GetPresenceRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BatchGetPresence
     */
    batchGetPresence(input: BatchGetPresenceReq, options?: RpcOptions): UnaryCall<BatchGetPresenceReq, BatchGetPresenceRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<BatchGetPresenceReq, BatchGetPresenceRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SubscribePresence
     */
    subscribePresence(input: SubscribeReq, options?: RpcOptions): UnaryCall<SubscribeReq, SubscribeRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<SubscribeReq, SubscribeRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnsubscribePresence
     */
    unsubscribePresence(input: UnsubscribeReq, options?: RpcOptions): UnaryCall<UnsubscribeReq, UnsubscribeRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnsubscribeReq, UnsubscribeRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendTyping
     */
    sendTyping(input: TypingReq, options?: RpcOptions): UnaryCall<TypingReq, TypingRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<TypingReq, TypingRsp>("unary", this._transport, method, opt, input);
    }
}
