// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "presence/presence_service.proto" (package "chatnow.presence", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ResponseHeader } from "../common/envelope";
import { DevicePlatform } from "../common/types";
/**
 * @generated from protobuf message chatnow.presence.DevicePresence
 */
export interface DevicePresence {
    /**
     * @generated from protobuf field: string device_id = 1
     */
    deviceId: string;
    /**
     * @generated from protobuf field: chatnow.common.DevicePlatform platform = 2
     */
    platform: DevicePlatform;
    /**
     * @generated from protobuf field: chatnow.presence.PresenceState state = 3
     */
    state: PresenceState;
    /**
     * @generated from protobuf field: int64 last_active_at_ms = 4
     */
    lastActiveAtMs: bigint;
}
/**
 * @generated from protobuf message chatnow.presence.Presence
 */
export interface Presence {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: chatnow.presence.PresenceState aggregated_state = 2
     */
    aggregatedState: PresenceState;
    /**
     * @generated from protobuf field: int64 last_active_at_ms = 3
     */
    lastActiveAtMs: bigint;
    /**
     * @generated from protobuf field: repeated chatnow.presence.DevicePresence devices = 4
     */
    devices: DevicePresence[];
}
/**
 * @generated from protobuf message chatnow.presence.GetPresenceReq
 */
export interface GetPresenceReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string; // 查询目标
}
/**
 * @generated from protobuf message chatnow.presence.GetPresenceRsp
 */
export interface GetPresenceRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.presence.Presence presence = 2
     */
    presence?: Presence;
}
/**
 * @generated from protobuf message chatnow.presence.BatchGetPresenceReq
 */
export interface BatchGetPresenceReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: repeated string user_ids = 2
     */
    userIds: string[];
}
/**
 * @generated from protobuf message chatnow.presence.BatchGetPresenceRsp
 */
export interface BatchGetPresenceRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: map<string, chatnow.presence.Presence> presences = 2
     */
    presences: {
        [key: string]: Presence;
    };
}
/**
 * @generated from protobuf message chatnow.presence.SubscribeReq
 */
export interface SubscribeReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: repeated string subscribe_user_ids = 2
     */
    subscribeUserIds: string[]; // subscriber_user_id 从 metadata 取
}
/**
 * @generated from protobuf message chatnow.presence.SubscribeRsp
 */
export interface SubscribeRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
}
/**
 * @generated from protobuf message chatnow.presence.UnsubscribeReq
 */
export interface UnsubscribeReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: repeated string unsubscribe_user_ids = 2
     */
    unsubscribeUserIds: string[]; // subscriber_user_id 从 metadata 取
}
/**
 * @generated from protobuf message chatnow.presence.UnsubscribeRsp
 */
export interface UnsubscribeRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
}
/**
 * @generated from protobuf message chatnow.presence.TypingReq
 */
export interface TypingReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string conversation_id = 2
     */
    conversationId: string;
    /**
     * @generated from protobuf field: bool is_typing = 3
     */
    isTyping: boolean; // user_id、device_id 从 metadata 取
}
/**
 * @generated from protobuf message chatnow.presence.TypingRsp
 */
export interface TypingRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
}
/**
 * @generated from protobuf enum chatnow.presence.PresenceState
 */
export enum PresenceState {
    /**
     * @generated from protobuf enum value: PRESENCE_UNSPECIFIED = 0;
     */
    PRESENCE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ONLINE = 1;
     */
    ONLINE = 1,
    /**
     * @generated from protobuf enum value: AWAY = 2;
     */
    AWAY = 2,
    /**
     * @generated from protobuf enum value: BUSY = 3;
     */
    BUSY = 3,
    /**
     * @generated from protobuf enum value: OFFLINE = 4;
     */
    OFFLINE = 4,
    /**
     * @generated from protobuf enum value: INVISIBLE = 5;
     */
    INVISIBLE = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class DevicePresence$Type extends MessageType<DevicePresence> {
    constructor() {
        super("chatnow.presence.DevicePresence", [
            { no: 1, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "platform", kind: "enum", T: () => ["chatnow.common.DevicePlatform", DevicePlatform] },
            { no: 3, name: "state", kind: "enum", T: () => ["chatnow.presence.PresenceState", PresenceState] },
            { no: 4, name: "last_active_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DevicePresence>): DevicePresence {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.deviceId = "";
        message.platform = 0;
        message.state = 0;
        message.lastActiveAtMs = 0n;
        if (value !== undefined)
            reflectionMergePartial<DevicePresence>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DevicePresence): DevicePresence {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string device_id */ 1:
                    message.deviceId = reader.string();
                    break;
                case /* chatnow.common.DevicePlatform platform */ 2:
                    message.platform = reader.int32() as any;
                    break;
                case /* chatnow.presence.PresenceState state */ 3:
                    message.state = reader.int32();
                    break;
                case /* int64 last_active_at_ms */ 4:
                    message.lastActiveAtMs = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DevicePresence, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string device_id = 1; */
        if (message.deviceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceId);
        /* chatnow.common.DevicePlatform platform = 2; */
        if (message.platform !== 0)
            writer.tag(2, WireType.Varint).int32(message.platform);
        /* chatnow.presence.PresenceState state = 3; */
        if (message.state !== 0)
            writer.tag(3, WireType.Varint).int32(message.state);
        /* int64 last_active_at_ms = 4; */
        if (message.lastActiveAtMs !== 0n)
            writer.tag(4, WireType.Varint).int64(message.lastActiveAtMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.DevicePresence
 */
export const DevicePresence = new DevicePresence$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Presence$Type extends MessageType<Presence> {
    constructor() {
        super("chatnow.presence.Presence", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "aggregated_state", kind: "enum", T: () => ["chatnow.presence.PresenceState", PresenceState] },
            { no: 3, name: "last_active_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "devices", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DevicePresence }
        ]);
    }
    create(value?: PartialMessage<Presence>): Presence {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.aggregatedState = 0;
        message.lastActiveAtMs = 0n;
        message.devices = [];
        if (value !== undefined)
            reflectionMergePartial<Presence>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Presence): Presence {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* chatnow.presence.PresenceState aggregated_state */ 2:
                    message.aggregatedState = reader.int32();
                    break;
                case /* int64 last_active_at_ms */ 3:
                    message.lastActiveAtMs = reader.int64().toBigInt();
                    break;
                case /* repeated chatnow.presence.DevicePresence devices */ 4:
                    message.devices.push(DevicePresence.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Presence, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* chatnow.presence.PresenceState aggregated_state = 2; */
        if (message.aggregatedState !== 0)
            writer.tag(2, WireType.Varint).int32(message.aggregatedState);
        /* int64 last_active_at_ms = 3; */
        if (message.lastActiveAtMs !== 0n)
            writer.tag(3, WireType.Varint).int64(message.lastActiveAtMs);
        /* repeated chatnow.presence.DevicePresence devices = 4; */
        for (let i = 0; i < message.devices.length; i++)
            DevicePresence.internalBinaryWrite(message.devices[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.Presence
 */
export const Presence = new Presence$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPresenceReq$Type extends MessageType<GetPresenceReq> {
    constructor() {
        super("chatnow.presence.GetPresenceReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPresenceReq>): GetPresenceReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<GetPresenceReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPresenceReq): GetPresenceReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPresenceReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.GetPresenceReq
 */
export const GetPresenceReq = new GetPresenceReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPresenceRsp$Type extends MessageType<GetPresenceRsp> {
    constructor() {
        super("chatnow.presence.GetPresenceRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "presence", kind: "message", T: () => Presence }
        ]);
    }
    create(value?: PartialMessage<GetPresenceRsp>): GetPresenceRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPresenceRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPresenceRsp): GetPresenceRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.presence.Presence presence */ 2:
                    message.presence = Presence.internalBinaryRead(reader, reader.uint32(), options, message.presence);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPresenceRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.presence.Presence presence = 2; */
        if (message.presence)
            Presence.internalBinaryWrite(message.presence, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.GetPresenceRsp
 */
export const GetPresenceRsp = new GetPresenceRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchGetPresenceReq$Type extends MessageType<BatchGetPresenceReq> {
    constructor() {
        super("chatnow.presence.BatchGetPresenceReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BatchGetPresenceReq>): BatchGetPresenceReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.userIds = [];
        if (value !== undefined)
            reflectionMergePartial<BatchGetPresenceReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchGetPresenceReq): BatchGetPresenceReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* repeated string user_ids */ 2:
                    message.userIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchGetPresenceReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* repeated string user_ids = 2; */
        for (let i = 0; i < message.userIds.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.userIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.BatchGetPresenceReq
 */
export const BatchGetPresenceReq = new BatchGetPresenceReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchGetPresenceRsp$Type extends MessageType<BatchGetPresenceRsp> {
    constructor() {
        super("chatnow.presence.BatchGetPresenceRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "presences", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => Presence } }
        ]);
    }
    create(value?: PartialMessage<BatchGetPresenceRsp>): BatchGetPresenceRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.presences = {};
        if (value !== undefined)
            reflectionMergePartial<BatchGetPresenceRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchGetPresenceRsp): BatchGetPresenceRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* map<string, chatnow.presence.Presence> presences */ 2:
                    this.binaryReadMap2(message.presences, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: BatchGetPresenceRsp["presences"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof BatchGetPresenceRsp["presences"] | undefined, val: BatchGetPresenceRsp["presences"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, _wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = Presence.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for chatnow.presence.BatchGetPresenceRsp.presences");
            }
        }
        map[key ?? ""] = val ?? Presence.create();
    }
    internalBinaryWrite(message: BatchGetPresenceRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<string, chatnow.presence.Presence> presences = 2; */
        for (let k of globalThis.Object.keys(message.presences)) {
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            Presence.internalBinaryWrite(message.presences[k], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.BatchGetPresenceRsp
 */
export const BatchGetPresenceRsp = new BatchGetPresenceRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeReq$Type extends MessageType<SubscribeReq> {
    constructor() {
        super("chatnow.presence.SubscribeReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "subscribe_user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubscribeReq>): SubscribeReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.subscribeUserIds = [];
        if (value !== undefined)
            reflectionMergePartial<SubscribeReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscribeReq): SubscribeReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* repeated string subscribe_user_ids */ 2:
                    message.subscribeUserIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscribeReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* repeated string subscribe_user_ids = 2; */
        for (let i = 0; i < message.subscribeUserIds.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.subscribeUserIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.SubscribeReq
 */
export const SubscribeReq = new SubscribeReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeRsp$Type extends MessageType<SubscribeRsp> {
    constructor() {
        super("chatnow.presence.SubscribeRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader }
        ]);
    }
    create(value?: PartialMessage<SubscribeRsp>): SubscribeRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SubscribeRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscribeRsp): SubscribeRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscribeRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.SubscribeRsp
 */
export const SubscribeRsp = new SubscribeRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnsubscribeReq$Type extends MessageType<UnsubscribeReq> {
    constructor() {
        super("chatnow.presence.UnsubscribeReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "unsubscribe_user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UnsubscribeReq>): UnsubscribeReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.unsubscribeUserIds = [];
        if (value !== undefined)
            reflectionMergePartial<UnsubscribeReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnsubscribeReq): UnsubscribeReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* repeated string unsubscribe_user_ids */ 2:
                    message.unsubscribeUserIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnsubscribeReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* repeated string unsubscribe_user_ids = 2; */
        for (let i = 0; i < message.unsubscribeUserIds.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.unsubscribeUserIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.UnsubscribeReq
 */
export const UnsubscribeReq = new UnsubscribeReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnsubscribeRsp$Type extends MessageType<UnsubscribeRsp> {
    constructor() {
        super("chatnow.presence.UnsubscribeRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader }
        ]);
    }
    create(value?: PartialMessage<UnsubscribeRsp>): UnsubscribeRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UnsubscribeRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnsubscribeRsp): UnsubscribeRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnsubscribeRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.UnsubscribeRsp
 */
export const UnsubscribeRsp = new UnsubscribeRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TypingReq$Type extends MessageType<TypingReq> {
    constructor() {
        super("chatnow.presence.TypingReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "is_typing", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TypingReq>): TypingReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.conversationId = "";
        message.isTyping = false;
        if (value !== undefined)
            reflectionMergePartial<TypingReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TypingReq): TypingReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string conversation_id */ 2:
                    message.conversationId = reader.string();
                    break;
                case /* bool is_typing */ 3:
                    message.isTyping = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TypingReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string conversation_id = 2; */
        if (message.conversationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationId);
        /* bool is_typing = 3; */
        if (message.isTyping !== false)
            writer.tag(3, WireType.Varint).bool(message.isTyping);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.TypingReq
 */
export const TypingReq = new TypingReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TypingRsp$Type extends MessageType<TypingRsp> {
    constructor() {
        super("chatnow.presence.TypingRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader }
        ]);
    }
    create(value?: PartialMessage<TypingRsp>): TypingRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<TypingRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TypingRsp): TypingRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TypingRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.presence.TypingRsp
 */
export const TypingRsp = new TypingRsp$Type();
/**
 * @generated ServiceType for protobuf service chatnow.presence.PresenceService
 */
export const PresenceService = new ServiceType("chatnow.presence.PresenceService", [
    { name: "GetPresence", options: {}, I: GetPresenceReq, O: GetPresenceRsp },
    { name: "BatchGetPresence", options: {}, I: BatchGetPresenceReq, O: BatchGetPresenceRsp },
    { name: "SubscribePresence", options: {}, I: SubscribeReq, O: SubscribeRsp },
    { name: "UnsubscribePresence", options: {}, I: UnsubscribeReq, O: UnsubscribeRsp },
    { name: "SendTyping", options: {}, I: TypingReq, O: TypingRsp }
]);
