// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/envelope.proto" (package "chatnow.common", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message chatnow.common.ResponseHeader
 */
export interface ResponseHeader {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: bool success = 2
     */
    success: boolean;
    /**
     * @generated from protobuf field: int32 error_code = 3
     */
    errorCode: number;
    /**
     * @generated from protobuf field: string error_message = 4
     */
    errorMessage: string;
}
/**
 * @generated from protobuf message chatnow.common.PageRequest
 */
export interface PageRequest {
    /**
     * @generated from protobuf field: int32 limit = 1
     */
    limit: number;
    /**
     * @generated from protobuf field: string cursor = 2
     */
    cursor: string;
}
/**
 * @generated from protobuf message chatnow.common.PageResponse
 */
export interface PageResponse {
    /**
     * @generated from protobuf field: bool has_more = 1
     */
    hasMore: boolean;
    /**
     * @generated from protobuf field: string next_cursor = 2
     */
    nextCursor: string;
    /**
     * @generated from protobuf field: int32 total_count = 3
     */
    totalCount: number;
}
/**
 * @generated from protobuf message chatnow.common.TimeRange
 */
export interface TimeRange {
    /**
     * @generated from protobuf field: int64 start_time_ms = 1
     */
    startTimeMs: bigint;
    /**
     * @generated from protobuf field: int64 end_time_ms = 2
     */
    endTimeMs: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class ResponseHeader$Type extends MessageType<ResponseHeader> {
    constructor() {
        super("chatnow.common.ResponseHeader", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "error_code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "error_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ResponseHeader>): ResponseHeader {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.success = false;
        message.errorCode = 0;
        message.errorMessage = "";
        if (value !== undefined)
            reflectionMergePartial<ResponseHeader>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ResponseHeader): ResponseHeader {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* bool success */ 2:
                    message.success = reader.bool();
                    break;
                case /* int32 error_code */ 3:
                    message.errorCode = reader.int32();
                    break;
                case /* string error_message */ 4:
                    message.errorMessage = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ResponseHeader, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* bool success = 2; */
        if (message.success !== false)
            writer.tag(2, WireType.Varint).bool(message.success);
        /* int32 error_code = 3; */
        if (message.errorCode !== 0)
            writer.tag(3, WireType.Varint).int32(message.errorCode);
        /* string error_message = 4; */
        if (message.errorMessage !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.errorMessage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.common.ResponseHeader
 */
export const ResponseHeader = new ResponseHeader$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageRequest$Type extends MessageType<PageRequest> {
    constructor() {
        super("chatnow.common.PageRequest", [
            { no: 1, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PageRequest>): PageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.limit = 0;
        message.cursor = "";
        if (value !== undefined)
            reflectionMergePartial<PageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageRequest): PageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 limit */ 1:
                    message.limit = reader.int32();
                    break;
                case /* string cursor */ 2:
                    message.cursor = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 limit = 1; */
        if (message.limit !== 0)
            writer.tag(1, WireType.Varint).int32(message.limit);
        /* string cursor = 2; */
        if (message.cursor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.cursor);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.common.PageRequest
 */
export const PageRequest = new PageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageResponse$Type extends MessageType<PageResponse> {
    constructor() {
        super("chatnow.common.PageResponse", [
            { no: 1, name: "has_more", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "next_cursor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<PageResponse>): PageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hasMore = false;
        message.nextCursor = "";
        message.totalCount = 0;
        if (value !== undefined)
            reflectionMergePartial<PageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageResponse): PageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool has_more */ 1:
                    message.hasMore = reader.bool();
                    break;
                case /* string next_cursor */ 2:
                    message.nextCursor = reader.string();
                    break;
                case /* int32 total_count */ 3:
                    message.totalCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool has_more = 1; */
        if (message.hasMore !== false)
            writer.tag(1, WireType.Varint).bool(message.hasMore);
        /* string next_cursor = 2; */
        if (message.nextCursor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.nextCursor);
        /* int32 total_count = 3; */
        if (message.totalCount !== 0)
            writer.tag(3, WireType.Varint).int32(message.totalCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.common.PageResponse
 */
export const PageResponse = new PageResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TimeRange$Type extends MessageType<TimeRange> {
    constructor() {
        super("chatnow.common.TimeRange", [
            { no: 1, name: "start_time_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "end_time_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<TimeRange>): TimeRange {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.startTimeMs = 0n;
        message.endTimeMs = 0n;
        if (value !== undefined)
            reflectionMergePartial<TimeRange>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TimeRange): TimeRange {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 start_time_ms */ 1:
                    message.startTimeMs = reader.int64().toBigInt();
                    break;
                case /* int64 end_time_ms */ 2:
                    message.endTimeMs = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TimeRange, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 start_time_ms = 1; */
        if (message.startTimeMs !== 0n)
            writer.tag(1, WireType.Varint).int64(message.startTimeMs);
        /* int64 end_time_ms = 2; */
        if (message.endTimeMs !== 0n)
            writer.tag(2, WireType.Varint).int64(message.endTimeMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.common.TimeRange
 */
export const TimeRange = new TimeRange$Type();
