// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/types.proto" (package "chatnow.common", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message chatnow.common.UserInfo
 */
export interface UserInfo {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string nickname = 2
     */
    nickname: string;
    /**
     * @generated from protobuf field: string bio = 3
     */
    bio: string;
    /**
     * @generated from protobuf field: string phone = 4
     */
    phone: string;
    /**
     * @generated from protobuf field: string avatar_url = 5
     */
    avatarUrl: string;
}
/**
 * @generated from protobuf enum chatnow.common.DevicePlatform
 */
export const DevicePlatform = {
    /**
     * @generated from protobuf enum value: DEVICE_PLATFORM_UNSPECIFIED = 0;
     */
    DEVICE_PLATFORM_UNSPECIFIED: 0,
    /**
     * @generated from protobuf enum value: IOS = 1;
     */
    IOS: 1,
    /**
     * @generated from protobuf enum value: ANDROID = 2;
     */
    ANDROID: 2,
    /**
     * @generated from protobuf enum value: WEB = 3;
     */
    WEB: 3,
    /**
     * @generated from protobuf enum value: DESKTOP_WIN = 4;
     */
    DESKTOP_WIN: 4,
    /**
     * @generated from protobuf enum value: DESKTOP_MAC = 5;
     */
    DESKTOP_MAC: 5,
    /**
     * @generated from protobuf enum value: DESKTOP_LINUX = 6;
     */
    DESKTOP_LINUX: 6,
} as const;

export type DevicePlatform = (typeof DevicePlatform)[keyof typeof DevicePlatform];
// @generated message type with reflection information, may provide speed optimized methods
class UserInfo$Type extends MessageType<UserInfo> {
    constructor() {
        super("chatnow.common.UserInfo", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "nickname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bio", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "avatar_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UserInfo>): UserInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.nickname = "";
        message.bio = "";
        message.phone = "";
        message.avatarUrl = "";
        if (value !== undefined)
            reflectionMergePartial<UserInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserInfo): UserInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string nickname */ 2:
                    message.nickname = reader.string();
                    break;
                case /* string bio */ 3:
                    message.bio = reader.string();
                    break;
                case /* string phone */ 4:
                    message.phone = reader.string();
                    break;
                case /* string avatar_url */ 5:
                    message.avatarUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string nickname = 2; */
        if (message.nickname !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.nickname);
        /* string bio = 3; */
        if (message.bio !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.bio);
        /* string phone = 4; */
        if (message.phone !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.phone);
        /* string avatar_url = 5; */
        if (message.avatarUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.avatarUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.common.UserInfo
 */
export const UserInfo = new UserInfo$Type();
