// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "identity/identity_service.proto" (package "chatnow.identity", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IdentityService } from "./identity_service";
import type { GetMultiUserInfoRsp } from "./identity_service";
import type { GetMultiUserInfoReq } from "./identity_service";
import type { SearchUsersRsp } from "./identity_service";
import type { SearchUsersReq } from "./identity_service";
import type { UpdateProfileRsp } from "./identity_service";
import type { UpdateProfileReq } from "./identity_service";
import type { GetProfileRsp } from "./identity_service";
import type { GetProfileReq } from "./identity_service";
import type { RefreshTokenRsp } from "./identity_service";
import type { RefreshTokenReq } from "./identity_service";
import type { SendVerifyCodeRsp } from "./identity_service";
import type { SendVerifyCodeReq } from "./identity_service";
import type { LogoutRsp } from "./identity_service";
import type { LogoutReq } from "./identity_service";
import type { LoginRsp } from "./identity_service";
import type { LoginReq } from "./identity_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RegisterRsp } from "./identity_service";
import type { RegisterReq } from "./identity_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.identity.IdentityService
 */
export interface IIdentityServiceClient {
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterReq, options?: RpcOptions): UnaryCall<RegisterReq, RegisterRsp>;
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginRsp>;
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutReq, options?: RpcOptions): UnaryCall<LogoutReq, LogoutRsp>;
    /**
     * @generated from protobuf rpc: SendVerifyCode
     */
    sendVerifyCode(input: SendVerifyCodeReq, options?: RpcOptions): UnaryCall<SendVerifyCodeReq, SendVerifyCodeRsp>;
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: RefreshTokenReq, options?: RpcOptions): UnaryCall<RefreshTokenReq, RefreshTokenRsp>;
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileReq, options?: RpcOptions): UnaryCall<GetProfileReq, GetProfileRsp>;
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileReq, options?: RpcOptions): UnaryCall<UpdateProfileReq, UpdateProfileRsp>;
    /**
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersReq, options?: RpcOptions): UnaryCall<SearchUsersReq, SearchUsersRsp>;
    /**
     * @generated from protobuf rpc: GetMultiUserInfo
     */
    getMultiUserInfo(input: GetMultiUserInfoReq, options?: RpcOptions): UnaryCall<GetMultiUserInfoReq, GetMultiUserInfoRsp>;
}
/**
 * @generated from protobuf service chatnow.identity.IdentityService
 */
export class IdentityServiceClient implements IIdentityServiceClient, ServiceInfo {
    typeName = IdentityService.typeName;
    methods = IdentityService.methods;
    options = IdentityService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Register
     */
    register(input: RegisterReq, options?: RpcOptions): UnaryCall<RegisterReq, RegisterRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterReq, RegisterRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginReq, LoginRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutReq, options?: RpcOptions): UnaryCall<LogoutReq, LogoutRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutReq, LogoutRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendVerifyCode
     */
    sendVerifyCode(input: SendVerifyCodeReq, options?: RpcOptions): UnaryCall<SendVerifyCodeReq, SendVerifyCodeRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendVerifyCodeReq, SendVerifyCodeRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RefreshToken
     */
    refreshToken(input: RefreshTokenReq, options?: RpcOptions): UnaryCall<RefreshTokenReq, RefreshTokenRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshTokenReq, RefreshTokenRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileReq, options?: RpcOptions): UnaryCall<GetProfileReq, GetProfileRsp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileReq, GetProfileRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileReq, options?: RpcOptions): UnaryCall<UpdateProfileReq, UpdateProfileRsp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileReq, UpdateProfileRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersReq, options?: RpcOptions): UnaryCall<SearchUsersReq, SearchUsersRsp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchUsersReq, SearchUsersRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMultiUserInfo
     */
    getMultiUserInfo(input: GetMultiUserInfoReq, options?: RpcOptions): UnaryCall<GetMultiUserInfoReq, GetMultiUserInfoRsp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMultiUserInfoReq, GetMultiUserInfoRsp>("unary", this._transport, method, opt, input);
    }
}
