// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "identity/identity_service.proto" (package "chatnow.identity", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { UserInfo } from "../common/types";
import { ResponseHeader } from "../common/envelope";
// ========== 通用鉴权产物（横切 spec §2.4） ==========

/**
 * @generated from protobuf message chatnow.identity.AuthTokens
 */
export interface AuthTokens {
    /**
     * @generated from protobuf field: string access_token = 1
     */
    accessToken: string;
    /**
     * @generated from protobuf field: string refresh_token = 2
     */
    refreshToken: string;
    /**
     * @generated from protobuf field: int32 access_expires_in_sec = 3
     */
    accessExpiresInSec: number;
    /**
     * @generated from protobuf field: int32 refresh_expires_in_sec = 4
     */
    refreshExpiresInSec: number;
}
// ========== Credential ==========

/**
 * @generated from protobuf message chatnow.identity.UsernamePassword
 */
export interface UsernamePassword {
    /**
     * @generated from protobuf field: string username = 1
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 2
     */
    password: string;
}
/**
 * @generated from protobuf message chatnow.identity.PhoneVerifyCode
 */
export interface PhoneVerifyCode {
    /**
     * @generated from protobuf field: string phone = 1
     */
    phone: string;
    /**
     * @generated from protobuf field: string verify_code_id = 2
     */
    verifyCodeId: string;
    /**
     * @generated from protobuf field: string verify_code = 3
     */
    verifyCode: string;
}
// ========== Register ==========

/**
 * @generated from protobuf message chatnow.identity.RegisterReq
 */
export interface RegisterReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf oneof: credential
     */
    credential: {
        oneofKind: "usernamePwd";
        /**
         * @generated from protobuf field: chatnow.identity.UsernamePassword username_pwd = 2
         */
        usernamePwd: UsernamePassword;
    } | {
        oneofKind: "phoneCode";
        /**
         * @generated from protobuf field: chatnow.identity.PhoneVerifyCode phone_code = 3
         */
        phoneCode: PhoneVerifyCode;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: string nickname = 4
     */
    nickname: string;
}
/**
 * @generated from protobuf message chatnow.identity.RegisterRsp
 */
export interface RegisterRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string user_id = 2
     */
    userId: string;
    /**
     * @generated from protobuf field: chatnow.identity.AuthTokens tokens = 3
     */
    tokens?: AuthTokens;
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 4
     */
    userInfo?: UserInfo;
}
// ========== Login ==========

/**
 * @generated from protobuf message chatnow.identity.LoginReq
 */
export interface LoginReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf oneof: credential
     */
    credential: {
        oneofKind: "usernamePwd";
        /**
         * @generated from protobuf field: chatnow.identity.UsernamePassword username_pwd = 2
         */
        usernamePwd: UsernamePassword;
    } | {
        oneofKind: "phoneCode";
        /**
         * @generated from protobuf field: chatnow.identity.PhoneVerifyCode phone_code = 3
         */
        phoneCode: PhoneVerifyCode;
    } | {
        oneofKind: undefined;
    };
    /**
     * device 模型（多端策略 / 撤销）属于 P3。
     * P2 仅把 device_id 透传进 JWT payload；P3 落地时收紧校验。
     *
     * @generated from protobuf field: string device_id = 4
     */
    deviceId: string;
    /**
     * @generated from protobuf field: string device_name = 5
     */
    deviceName: string;
}
/**
 * @generated from protobuf message chatnow.identity.LoginRsp
 */
export interface LoginRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.identity.AuthTokens tokens = 2
     */
    tokens?: AuthTokens;
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 3
     */
    userInfo?: UserInfo;
}
// ========== Logout ==========

/**
 * user_id / device_id 从 brpc metadata 读，不在 body
 *
 * @generated from protobuf message chatnow.identity.LogoutReq
 */
export interface LogoutReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
}
/**
 * @generated from protobuf message chatnow.identity.LogoutRsp
 */
export interface LogoutRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
}
// ========== SendVerifyCode ==========

/**
 * @generated from protobuf message chatnow.identity.SendVerifyCodeReq
 */
export interface SendVerifyCodeReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf oneof: destination
     */
    destination: {
        oneofKind: "email";
        /**
         * @generated from protobuf field: string email = 2
         */
        email: string;
    } | {
        oneofKind: "phone";
        /**
         * @generated from protobuf field: string phone = 3
         */
        phone: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message chatnow.identity.SendVerifyCodeRsp
 */
export interface SendVerifyCodeRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: string verify_code_id = 2
     */
    verifyCodeId: string;
}
// ========== RefreshToken ==========

/**
 * @generated from protobuf message chatnow.identity.RefreshTokenReq
 */
export interface RefreshTokenReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string refresh_token = 2
     */
    refreshToken: string;
}
/**
 * @generated from protobuf message chatnow.identity.RefreshTokenRsp
 */
export interface RefreshTokenRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.identity.AuthTokens tokens = 2
     */
    tokens?: AuthTokens;
}
// ========== Profile / Search（保留；§2.8 字段清理是后续 plan） ==========

/**
 * @generated from protobuf message chatnow.identity.GetProfileReq
 */
export interface GetProfileReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: optional string user_id = 2
     */
    userId?: string; // 空=查自己
}
/**
 * @generated from protobuf message chatnow.identity.GetProfileRsp
 */
export interface GetProfileRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 2
     */
    userInfo?: UserInfo;
}
/**
 * @generated from protobuf message chatnow.identity.UpdateProfileReq
 */
export interface UpdateProfileReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: optional string nickname = 2
     */
    nickname?: string;
    /**
     * @generated from protobuf field: optional string bio = 3
     */
    bio?: string;
    /**
     * @generated from protobuf field: optional string avatar_file_id = 4
     */
    avatarFileId?: string;
    /**
     * @generated from protobuf field: optional string phone = 5
     */
    phone?: string;
}
/**
 * @generated from protobuf message chatnow.identity.UpdateProfileRsp
 */
export interface UpdateProfileRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.common.UserInfo user_info = 2
     */
    userInfo?: UserInfo;
}
/**
 * @generated from protobuf message chatnow.identity.SearchUsersReq
 */
export interface SearchUsersReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string search_key = 2
     */
    searchKey: string;
}
/**
 * @generated from protobuf message chatnow.identity.SearchUsersRsp
 */
export interface SearchUsersRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: repeated chatnow.common.UserInfo user_info = 2
     */
    userInfo: UserInfo[];
}
/**
 * @generated from protobuf message chatnow.identity.GetMultiUserInfoReq
 */
export interface GetMultiUserInfoReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: repeated string users_id = 2
     */
    usersId: string[];
}
/**
 * @generated from protobuf message chatnow.identity.GetMultiUserInfoRsp
 */
export interface GetMultiUserInfoRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: map<string, chatnow.common.UserInfo> users_info = 2
     */
    usersInfo: {
        [key: string]: UserInfo;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class AuthTokens$Type extends MessageType<AuthTokens> {
    constructor() {
        super("chatnow.identity.AuthTokens", [
            { no: 1, name: "access_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "access_expires_in_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "refresh_expires_in_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AuthTokens>): AuthTokens {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accessToken = "";
        message.refreshToken = "";
        message.accessExpiresInSec = 0;
        message.refreshExpiresInSec = 0;
        if (value !== undefined)
            reflectionMergePartial<AuthTokens>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthTokens): AuthTokens {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string access_token */ 1:
                    message.accessToken = reader.string();
                    break;
                case /* string refresh_token */ 2:
                    message.refreshToken = reader.string();
                    break;
                case /* int32 access_expires_in_sec */ 3:
                    message.accessExpiresInSec = reader.int32();
                    break;
                case /* int32 refresh_expires_in_sec */ 4:
                    message.refreshExpiresInSec = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthTokens, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string access_token = 1; */
        if (message.accessToken !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.accessToken);
        /* string refresh_token = 2; */
        if (message.refreshToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refreshToken);
        /* int32 access_expires_in_sec = 3; */
        if (message.accessExpiresInSec !== 0)
            writer.tag(3, WireType.Varint).int32(message.accessExpiresInSec);
        /* int32 refresh_expires_in_sec = 4; */
        if (message.refreshExpiresInSec !== 0)
            writer.tag(4, WireType.Varint).int32(message.refreshExpiresInSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.AuthTokens
 */
export const AuthTokens = new AuthTokens$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UsernamePassword$Type extends MessageType<UsernamePassword> {
    constructor() {
        super("chatnow.identity.UsernamePassword", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UsernamePassword>): UsernamePassword {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.username = "";
        message.password = "";
        if (value !== undefined)
            reflectionMergePartial<UsernamePassword>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UsernamePassword): UsernamePassword {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string username */ 1:
                    message.username = reader.string();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UsernamePassword, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string username = 1; */
        if (message.username !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.username);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.UsernamePassword
 */
export const UsernamePassword = new UsernamePassword$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PhoneVerifyCode$Type extends MessageType<PhoneVerifyCode> {
    constructor() {
        super("chatnow.identity.PhoneVerifyCode", [
            { no: 1, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "verify_code_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "verify_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PhoneVerifyCode>): PhoneVerifyCode {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.phone = "";
        message.verifyCodeId = "";
        message.verifyCode = "";
        if (value !== undefined)
            reflectionMergePartial<PhoneVerifyCode>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PhoneVerifyCode): PhoneVerifyCode {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string phone */ 1:
                    message.phone = reader.string();
                    break;
                case /* string verify_code_id */ 2:
                    message.verifyCodeId = reader.string();
                    break;
                case /* string verify_code */ 3:
                    message.verifyCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PhoneVerifyCode, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string phone = 1; */
        if (message.phone !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.phone);
        /* string verify_code_id = 2; */
        if (message.verifyCodeId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.verifyCodeId);
        /* string verify_code = 3; */
        if (message.verifyCode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.verifyCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.PhoneVerifyCode
 */
export const PhoneVerifyCode = new PhoneVerifyCode$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterReq$Type extends MessageType<RegisterReq> {
    constructor() {
        super("chatnow.identity.RegisterReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "username_pwd", kind: "message", oneof: "credential", T: () => UsernamePassword },
            { no: 3, name: "phone_code", kind: "message", oneof: "credential", T: () => PhoneVerifyCode },
            { no: 4, name: "nickname", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterReq>): RegisterReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.credential = { oneofKind: undefined };
        message.nickname = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterReq): RegisterReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* chatnow.identity.UsernamePassword username_pwd */ 2:
                    message.credential = {
                        oneofKind: "usernamePwd",
                        usernamePwd: UsernamePassword.internalBinaryRead(reader, reader.uint32(), options, (message.credential as any).usernamePwd)
                    };
                    break;
                case /* chatnow.identity.PhoneVerifyCode phone_code */ 3:
                    message.credential = {
                        oneofKind: "phoneCode",
                        phoneCode: PhoneVerifyCode.internalBinaryRead(reader, reader.uint32(), options, (message.credential as any).phoneCode)
                    };
                    break;
                case /* string nickname */ 4:
                    message.nickname = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* chatnow.identity.UsernamePassword username_pwd = 2; */
        if (message.credential.oneofKind === "usernamePwd")
            UsernamePassword.internalBinaryWrite(message.credential.usernamePwd, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.identity.PhoneVerifyCode phone_code = 3; */
        if (message.credential.oneofKind === "phoneCode")
            PhoneVerifyCode.internalBinaryWrite(message.credential.phoneCode, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string nickname = 4; */
        if (message.nickname !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.nickname);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.RegisterReq
 */
export const RegisterReq = new RegisterReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterRsp$Type extends MessageType<RegisterRsp> {
    constructor() {
        super("chatnow.identity.RegisterRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tokens", kind: "message", T: () => AuthTokens },
            { no: 4, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<RegisterRsp>): RegisterRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<RegisterRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterRsp): RegisterRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string user_id */ 2:
                    message.userId = reader.string();
                    break;
                case /* chatnow.identity.AuthTokens tokens */ 3:
                    message.tokens = AuthTokens.internalBinaryRead(reader, reader.uint32(), options, message.tokens);
                    break;
                case /* chatnow.common.UserInfo user_info */ 4:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string user_id = 2; */
        if (message.userId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        /* chatnow.identity.AuthTokens tokens = 3; */
        if (message.tokens)
            AuthTokens.internalBinaryWrite(message.tokens, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.common.UserInfo user_info = 4; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.RegisterRsp
 */
export const RegisterRsp = new RegisterRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginReq$Type extends MessageType<LoginReq> {
    constructor() {
        super("chatnow.identity.LoginReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "username_pwd", kind: "message", oneof: "credential", T: () => UsernamePassword },
            { no: 3, name: "phone_code", kind: "message", oneof: "credential", T: () => PhoneVerifyCode },
            { no: 4, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "device_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LoginReq>): LoginReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.credential = { oneofKind: undefined };
        message.deviceId = "";
        message.deviceName = "";
        if (value !== undefined)
            reflectionMergePartial<LoginReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginReq): LoginReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* chatnow.identity.UsernamePassword username_pwd */ 2:
                    message.credential = {
                        oneofKind: "usernamePwd",
                        usernamePwd: UsernamePassword.internalBinaryRead(reader, reader.uint32(), options, (message.credential as any).usernamePwd)
                    };
                    break;
                case /* chatnow.identity.PhoneVerifyCode phone_code */ 3:
                    message.credential = {
                        oneofKind: "phoneCode",
                        phoneCode: PhoneVerifyCode.internalBinaryRead(reader, reader.uint32(), options, (message.credential as any).phoneCode)
                    };
                    break;
                case /* string device_id */ 4:
                    message.deviceId = reader.string();
                    break;
                case /* string device_name */ 5:
                    message.deviceName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* chatnow.identity.UsernamePassword username_pwd = 2; */
        if (message.credential.oneofKind === "usernamePwd")
            UsernamePassword.internalBinaryWrite(message.credential.usernamePwd, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.identity.PhoneVerifyCode phone_code = 3; */
        if (message.credential.oneofKind === "phoneCode")
            PhoneVerifyCode.internalBinaryWrite(message.credential.phoneCode, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string device_id = 4; */
        if (message.deviceId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.deviceId);
        /* string device_name = 5; */
        if (message.deviceName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.deviceName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.LoginReq
 */
export const LoginReq = new LoginReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginRsp$Type extends MessageType<LoginRsp> {
    constructor() {
        super("chatnow.identity.LoginRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "tokens", kind: "message", T: () => AuthTokens },
            { no: 3, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<LoginRsp>): LoginRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LoginRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRsp): LoginRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.identity.AuthTokens tokens */ 2:
                    message.tokens = AuthTokens.internalBinaryRead(reader, reader.uint32(), options, message.tokens);
                    break;
                case /* chatnow.common.UserInfo user_info */ 3:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.identity.AuthTokens tokens = 2; */
        if (message.tokens)
            AuthTokens.internalBinaryWrite(message.tokens, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.common.UserInfo user_info = 3; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.LoginRsp
 */
export const LoginRsp = new LoginRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutReq$Type extends MessageType<LogoutReq> {
    constructor() {
        super("chatnow.identity.LogoutReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LogoutReq>): LogoutReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        if (value !== undefined)
            reflectionMergePartial<LogoutReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutReq): LogoutReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.LogoutReq
 */
export const LogoutReq = new LogoutReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LogoutRsp$Type extends MessageType<LogoutRsp> {
    constructor() {
        super("chatnow.identity.LogoutRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader }
        ]);
    }
    create(value?: PartialMessage<LogoutRsp>): LogoutRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<LogoutRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LogoutRsp): LogoutRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LogoutRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.LogoutRsp
 */
export const LogoutRsp = new LogoutRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendVerifyCodeReq$Type extends MessageType<SendVerifyCodeReq> {
    constructor() {
        super("chatnow.identity.SendVerifyCodeReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", oneof: "destination", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "phone", kind: "scalar", oneof: "destination", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendVerifyCodeReq>): SendVerifyCodeReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.destination = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<SendVerifyCodeReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendVerifyCodeReq): SendVerifyCodeReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string email */ 2:
                    message.destination = {
                        oneofKind: "email",
                        email: reader.string()
                    };
                    break;
                case /* string phone */ 3:
                    message.destination = {
                        oneofKind: "phone",
                        phone: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendVerifyCodeReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string email = 2; */
        if (message.destination.oneofKind === "email")
            writer.tag(2, WireType.LengthDelimited).string(message.destination.email);
        /* string phone = 3; */
        if (message.destination.oneofKind === "phone")
            writer.tag(3, WireType.LengthDelimited).string(message.destination.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.SendVerifyCodeReq
 */
export const SendVerifyCodeReq = new SendVerifyCodeReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendVerifyCodeRsp$Type extends MessageType<SendVerifyCodeRsp> {
    constructor() {
        super("chatnow.identity.SendVerifyCodeRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "verify_code_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendVerifyCodeRsp>): SendVerifyCodeRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.verifyCodeId = "";
        if (value !== undefined)
            reflectionMergePartial<SendVerifyCodeRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendVerifyCodeRsp): SendVerifyCodeRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* string verify_code_id */ 2:
                    message.verifyCodeId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendVerifyCodeRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string verify_code_id = 2; */
        if (message.verifyCodeId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.verifyCodeId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.SendVerifyCodeRsp
 */
export const SendVerifyCodeRsp = new SendVerifyCodeRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenReq$Type extends MessageType<RefreshTokenReq> {
    constructor() {
        super("chatnow.identity.RefreshTokenReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "refresh_token", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenReq>): RefreshTokenReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.refreshToken = "";
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenReq): RefreshTokenReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string refresh_token */ 2:
                    message.refreshToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string refresh_token = 2; */
        if (message.refreshToken !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.refreshToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.RefreshTokenReq
 */
export const RefreshTokenReq = new RefreshTokenReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RefreshTokenRsp$Type extends MessageType<RefreshTokenRsp> {
    constructor() {
        super("chatnow.identity.RefreshTokenRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "tokens", kind: "message", T: () => AuthTokens }
        ]);
    }
    create(value?: PartialMessage<RefreshTokenRsp>): RefreshTokenRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RefreshTokenRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RefreshTokenRsp): RefreshTokenRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.identity.AuthTokens tokens */ 2:
                    message.tokens = AuthTokens.internalBinaryRead(reader, reader.uint32(), options, message.tokens);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RefreshTokenRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.identity.AuthTokens tokens = 2; */
        if (message.tokens)
            AuthTokens.internalBinaryWrite(message.tokens, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.RefreshTokenRsp
 */
export const RefreshTokenRsp = new RefreshTokenRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileReq$Type extends MessageType<GetProfileReq> {
    constructor() {
        super("chatnow.identity.GetProfileReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "user_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetProfileReq>): GetProfileReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        if (value !== undefined)
            reflectionMergePartial<GetProfileReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileReq): GetProfileReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* optional string user_id */ 2:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* optional string user_id = 2; */
        if (message.userId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.GetProfileReq
 */
export const GetProfileReq = new GetProfileReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileRsp$Type extends MessageType<GetProfileRsp> {
    constructor() {
        super("chatnow.identity.GetProfileRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<GetProfileRsp>): GetProfileRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetProfileRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileRsp): GetProfileRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.common.UserInfo user_info */ 2:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.common.UserInfo user_info = 2; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.GetProfileRsp
 */
export const GetProfileRsp = new GetProfileRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateProfileReq$Type extends MessageType<UpdateProfileReq> {
    constructor() {
        super("chatnow.identity.UpdateProfileReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "nickname", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bio", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "avatar_file_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "phone", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateProfileReq>): UpdateProfileReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateProfileReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateProfileReq): UpdateProfileReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* optional string nickname */ 2:
                    message.nickname = reader.string();
                    break;
                case /* optional string bio */ 3:
                    message.bio = reader.string();
                    break;
                case /* optional string avatar_file_id */ 4:
                    message.avatarFileId = reader.string();
                    break;
                case /* optional string phone */ 5:
                    message.phone = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateProfileReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* optional string nickname = 2; */
        if (message.nickname !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.nickname);
        /* optional string bio = 3; */
        if (message.bio !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.bio);
        /* optional string avatar_file_id = 4; */
        if (message.avatarFileId !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.avatarFileId);
        /* optional string phone = 5; */
        if (message.phone !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.UpdateProfileReq
 */
export const UpdateProfileReq = new UpdateProfileReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateProfileRsp$Type extends MessageType<UpdateProfileRsp> {
    constructor() {
        super("chatnow.identity.UpdateProfileRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "user_info", kind: "message", T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<UpdateProfileRsp>): UpdateProfileRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateProfileRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateProfileRsp): UpdateProfileRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.common.UserInfo user_info */ 2:
                    message.userInfo = UserInfo.internalBinaryRead(reader, reader.uint32(), options, message.userInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateProfileRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.common.UserInfo user_info = 2; */
        if (message.userInfo)
            UserInfo.internalBinaryWrite(message.userInfo, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.UpdateProfileRsp
 */
export const UpdateProfileRsp = new UpdateProfileRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsersReq$Type extends MessageType<SearchUsersReq> {
    constructor() {
        super("chatnow.identity.SearchUsersReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "search_key", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchUsersReq>): SearchUsersReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.searchKey = "";
        if (value !== undefined)
            reflectionMergePartial<SearchUsersReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsersReq): SearchUsersReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string search_key */ 2:
                    message.searchKey = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsersReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string search_key = 2; */
        if (message.searchKey !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.searchKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.SearchUsersReq
 */
export const SearchUsersReq = new SearchUsersReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchUsersRsp$Type extends MessageType<SearchUsersRsp> {
    constructor() {
        super("chatnow.identity.SearchUsersRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "user_info", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => UserInfo }
        ]);
    }
    create(value?: PartialMessage<SearchUsersRsp>): SearchUsersRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userInfo = [];
        if (value !== undefined)
            reflectionMergePartial<SearchUsersRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchUsersRsp): SearchUsersRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* repeated chatnow.common.UserInfo user_info */ 2:
                    message.userInfo.push(UserInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchUsersRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated chatnow.common.UserInfo user_info = 2; */
        for (let i = 0; i < message.userInfo.length; i++)
            UserInfo.internalBinaryWrite(message.userInfo[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.SearchUsersRsp
 */
export const SearchUsersRsp = new SearchUsersRsp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMultiUserInfoReq$Type extends MessageType<GetMultiUserInfoReq> {
    constructor() {
        super("chatnow.identity.GetMultiUserInfoReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "users_id", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMultiUserInfoReq>): GetMultiUserInfoReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.usersId = [];
        if (value !== undefined)
            reflectionMergePartial<GetMultiUserInfoReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMultiUserInfoReq): GetMultiUserInfoReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* repeated string users_id */ 2:
                    message.usersId.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMultiUserInfoReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* repeated string users_id = 2; */
        for (let i = 0; i < message.usersId.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.usersId[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.GetMultiUserInfoReq
 */
export const GetMultiUserInfoReq = new GetMultiUserInfoReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMultiUserInfoRsp$Type extends MessageType<GetMultiUserInfoRsp> {
    constructor() {
        super("chatnow.identity.GetMultiUserInfoRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "users_info", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => UserInfo } }
        ]);
    }
    create(value?: PartialMessage<GetMultiUserInfoRsp>): GetMultiUserInfoRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.usersInfo = {};
        if (value !== undefined)
            reflectionMergePartial<GetMultiUserInfoRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMultiUserInfoRsp): GetMultiUserInfoRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* map<string, chatnow.common.UserInfo> users_info */ 2:
                    this.binaryReadMap2(message.usersInfo, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: GetMultiUserInfoRsp["usersInfo"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof GetMultiUserInfoRsp["usersInfo"] | undefined, val: GetMultiUserInfoRsp["usersInfo"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = UserInfo.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for chatnow.identity.GetMultiUserInfoRsp.users_info");
            }
        }
        map[key ?? ""] = val ?? UserInfo.create();
    }
    internalBinaryWrite(message: GetMultiUserInfoRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<string, chatnow.common.UserInfo> users_info = 2; */
        for (let k of globalThis.Object.keys(message.usersInfo)) {
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            UserInfo.internalBinaryWrite(message.usersInfo[k], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.identity.GetMultiUserInfoRsp
 */
export const GetMultiUserInfoRsp = new GetMultiUserInfoRsp$Type();
/**
 * @generated ServiceType for protobuf service chatnow.identity.IdentityService
 */
export const IdentityService = new ServiceType("chatnow.identity.IdentityService", [
    { name: "Register", options: {}, I: RegisterReq, O: RegisterRsp },
    { name: "Login", options: {}, I: LoginReq, O: LoginRsp },
    { name: "Logout", options: {}, I: LogoutReq, O: LogoutRsp },
    { name: "SendVerifyCode", options: {}, I: SendVerifyCodeReq, O: SendVerifyCodeRsp },
    { name: "RefreshToken", options: {}, I: RefreshTokenReq, O: RefreshTokenRsp },
    { name: "GetProfile", options: {}, I: GetProfileReq, O: GetProfileRsp },
    { name: "UpdateProfile", options: {}, I: UpdateProfileReq, O: UpdateProfileRsp },
    { name: "SearchUsers", options: {}, I: SearchUsersReq, O: SearchUsersRsp },
    { name: "GetMultiUserInfo", options: {}, I: GetMultiUserInfoReq, O: GetMultiUserInfoRsp }
]);
