// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "message/message_service.proto" (package "chatnow.message", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MessageService } from "./message_service";
import type { UpdateReadAckRsp } from "./message_service";
import type { UpdateReadAckReq } from "./message_service";
import type { SelectByClientMsgIdRsp } from "./message_service";
import type { SelectByClientMsgIdReq } from "./message_service";
import type { ClearConversationRsp } from "./message_service";
import type { ClearConversationReq } from "./message_service";
import type { DeleteMessagesRsp } from "./message_service";
import type { DeleteMessagesReq } from "./message_service";
import type { ListPinnedRsp } from "./message_service";
import type { ListPinnedReq } from "./message_service";
import type { UnpinMessageRsp } from "./message_service";
import type { UnpinMessageReq } from "./message_service";
import type { PinMessageRsp } from "./message_service";
import type { PinMessageReq } from "./message_service";
import type { GetReactionsRsp } from "./message_service";
import type { GetReactionsReq } from "./message_service";
import type { RemoveReactionRsp } from "./message_service";
import type { RemoveReactionReq } from "./message_service";
import type { AddReactionRsp } from "./message_service";
import type { AddReactionReq } from "./message_service";
import type { RecallMessageRsp } from "./message_service";
import type { RecallMessageReq } from "./message_service";
import type { SearchMessagesRsp } from "./message_service";
import type { SearchMessagesReq } from "./message_service";
import type { GetMessagesByIdRsp } from "./message_service";
import type { GetMessagesByIdReq } from "./message_service";
import type { GetHistoryRsp } from "./message_service";
import type { GetHistoryReq } from "./message_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SyncMessagesRsp } from "./message_service";
import type { SyncMessagesReq } from "./message_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.message.MessageService
 */
export interface IMessageServiceClient {
    /**
     * @generated from protobuf rpc: SyncMessages
     */
    syncMessages(input: SyncMessagesReq, options?: RpcOptions): UnaryCall<SyncMessagesReq, SyncMessagesRsp>;
    /**
     * @generated from protobuf rpc: GetHistory
     */
    getHistory(input: GetHistoryReq, options?: RpcOptions): UnaryCall<GetHistoryReq, GetHistoryRsp>;
    /**
     * @generated from protobuf rpc: GetMessagesById
     */
    getMessagesById(input: GetMessagesByIdReq, options?: RpcOptions): UnaryCall<GetMessagesByIdReq, GetMessagesByIdRsp>;
    /**
     * @generated from protobuf rpc: SearchMessages
     */
    searchMessages(input: SearchMessagesReq, options?: RpcOptions): UnaryCall<SearchMessagesReq, SearchMessagesRsp>;
    /**
     * @generated from protobuf rpc: RecallMessage
     */
    recallMessage(input: RecallMessageReq, options?: RpcOptions): UnaryCall<RecallMessageReq, RecallMessageRsp>;
    /**
     * @generated from protobuf rpc: AddReaction
     */
    addReaction(input: AddReactionReq, options?: RpcOptions): UnaryCall<AddReactionReq, AddReactionRsp>;
    /**
     * @generated from protobuf rpc: RemoveReaction
     */
    removeReaction(input: RemoveReactionReq, options?: RpcOptions): UnaryCall<RemoveReactionReq, RemoveReactionRsp>;
    /**
     * @generated from protobuf rpc: GetReactions
     */
    getReactions(input: GetReactionsReq, options?: RpcOptions): UnaryCall<GetReactionsReq, GetReactionsRsp>;
    /**
     * @generated from protobuf rpc: PinMessage
     */
    pinMessage(input: PinMessageReq, options?: RpcOptions): UnaryCall<PinMessageReq, PinMessageRsp>;
    /**
     * @generated from protobuf rpc: UnpinMessage
     */
    unpinMessage(input: UnpinMessageReq, options?: RpcOptions): UnaryCall<UnpinMessageReq, UnpinMessageRsp>;
    /**
     * @generated from protobuf rpc: ListPinnedMessages
     */
    listPinnedMessages(input: ListPinnedReq, options?: RpcOptions): UnaryCall<ListPinnedReq, ListPinnedRsp>;
    /**
     * @generated from protobuf rpc: DeleteMessages
     */
    deleteMessages(input: DeleteMessagesReq, options?: RpcOptions): UnaryCall<DeleteMessagesReq, DeleteMessagesRsp>;
    /**
     * @generated from protobuf rpc: ClearConversation
     */
    clearConversation(input: ClearConversationReq, options?: RpcOptions): UnaryCall<ClearConversationReq, ClearConversationRsp>;
    /**
     * @generated from protobuf rpc: SelectByClientMsgId
     */
    selectByClientMsgId(input: SelectByClientMsgIdReq, options?: RpcOptions): UnaryCall<SelectByClientMsgIdReq, SelectByClientMsgIdRsp>;
    /**
     * @generated from protobuf rpc: UpdateReadAck
     */
    updateReadAck(input: UpdateReadAckReq, options?: RpcOptions): UnaryCall<UpdateReadAckReq, UpdateReadAckRsp>;
}
/**
 * @generated from protobuf service chatnow.message.MessageService
 */
export class MessageServiceClient implements IMessageServiceClient, ServiceInfo {
    typeName = MessageService.typeName;
    methods = MessageService.methods;
    options = MessageService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SyncMessages
     */
    syncMessages(input: SyncMessagesReq, options?: RpcOptions): UnaryCall<SyncMessagesReq, SyncMessagesRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SyncMessagesReq, SyncMessagesRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetHistory
     */
    getHistory(input: GetHistoryReq, options?: RpcOptions): UnaryCall<GetHistoryReq, GetHistoryRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetHistoryReq, GetHistoryRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMessagesById
     */
    getMessagesById(input: GetMessagesByIdReq, options?: RpcOptions): UnaryCall<GetMessagesByIdReq, GetMessagesByIdRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMessagesByIdReq, GetMessagesByIdRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchMessages
     */
    searchMessages(input: SearchMessagesReq, options?: RpcOptions): UnaryCall<SearchMessagesReq, SearchMessagesRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchMessagesReq, SearchMessagesRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RecallMessage
     */
    recallMessage(input: RecallMessageReq, options?: RpcOptions): UnaryCall<RecallMessageReq, RecallMessageRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RecallMessageReq, RecallMessageRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddReaction
     */
    addReaction(input: AddReactionReq, options?: RpcOptions): UnaryCall<AddReactionReq, AddReactionRsp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddReactionReq, AddReactionRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveReaction
     */
    removeReaction(input: RemoveReactionReq, options?: RpcOptions): UnaryCall<RemoveReactionReq, RemoveReactionRsp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveReactionReq, RemoveReactionRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReactions
     */
    getReactions(input: GetReactionsReq, options?: RpcOptions): UnaryCall<GetReactionsReq, GetReactionsRsp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetReactionsReq, GetReactionsRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PinMessage
     */
    pinMessage(input: PinMessageReq, options?: RpcOptions): UnaryCall<PinMessageReq, PinMessageRsp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<PinMessageReq, PinMessageRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnpinMessage
     */
    unpinMessage(input: UnpinMessageReq, options?: RpcOptions): UnaryCall<UnpinMessageReq, UnpinMessageRsp> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnpinMessageReq, UnpinMessageRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPinnedMessages
     */
    listPinnedMessages(input: ListPinnedReq, options?: RpcOptions): UnaryCall<ListPinnedReq, ListPinnedRsp> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPinnedReq, ListPinnedRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteMessages
     */
    deleteMessages(input: DeleteMessagesReq, options?: RpcOptions): UnaryCall<DeleteMessagesReq, DeleteMessagesRsp> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteMessagesReq, DeleteMessagesRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClearConversation
     */
    clearConversation(input: ClearConversationReq, options?: RpcOptions): UnaryCall<ClearConversationReq, ClearConversationRsp> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClearConversationReq, ClearConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SelectByClientMsgId
     */
    selectByClientMsgId(input: SelectByClientMsgIdReq, options?: RpcOptions): UnaryCall<SelectByClientMsgIdReq, SelectByClientMsgIdRsp> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<SelectByClientMsgIdReq, SelectByClientMsgIdRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateReadAck
     */
    updateReadAck(input: UpdateReadAckReq, options?: RpcOptions): UnaryCall<UpdateReadAckReq, UpdateReadAckRsp> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateReadAckReq, UpdateReadAckRsp>("unary", this._transport, method, opt, input);
    }
}
