// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "message/message_types.proto" (package "chatnow.message", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType as MessageType$ } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message chatnow.message.TextContent
 */
export interface TextContent {
    /**
     * @generated from protobuf field: string text = 1
     */
    text: string;
}
/**
 * @generated from protobuf message chatnow.message.ImageContent
 */
export interface ImageContent {
    /**
     * @generated from protobuf field: string file_id = 1
     */
    fileId: string;
    /**
     * @generated from protobuf field: int32 width = 2
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 3
     */
    height: number;
    /**
     * @generated from protobuf field: string thumbnail_url = 4
     */
    thumbnailUrl: string;
}
/**
 * @generated from protobuf message chatnow.message.FileContent
 */
export interface FileContent {
    /**
     * @generated from protobuf field: string file_id = 1
     */
    fileId: string;
    /**
     * @generated from protobuf field: string file_name = 2
     */
    fileName: string;
    /**
     * @generated from protobuf field: int64 file_size = 3
     */
    fileSize: bigint;
    /**
     * @generated from protobuf field: string mime_type = 4
     */
    mimeType: string;
}
/**
 * @generated from protobuf message chatnow.message.AudioContent
 */
export interface AudioContent {
    /**
     * @generated from protobuf field: string file_id = 1
     */
    fileId: string;
    /**
     * @generated from protobuf field: int32 duration_sec = 2
     */
    durationSec: number;
}
/**
 * @generated from protobuf message chatnow.message.VideoContent
 */
export interface VideoContent {
    /**
     * @generated from protobuf field: string file_id = 1
     */
    fileId: string;
    /**
     * @generated from protobuf field: int32 duration_sec = 2
     */
    durationSec: number;
    /**
     * @generated from protobuf field: int32 width = 3
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 4
     */
    height: number;
    /**
     * @generated from protobuf field: string thumbnail_url = 5
     */
    thumbnailUrl: string;
}
/**
 * @generated from protobuf message chatnow.message.LocationContent
 */
export interface LocationContent {
    /**
     * @generated from protobuf field: double latitude = 1
     */
    latitude: number;
    /**
     * @generated from protobuf field: double longitude = 2
     */
    longitude: number;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string address = 4
     */
    address: string;
}
/**
 * @generated from protobuf message chatnow.message.StickerContent
 */
export interface StickerContent {
    /**
     * @generated from protobuf field: string sticker_id = 1
     */
    stickerId: string;
    /**
     * @generated from protobuf field: string pack_id = 2
     */
    packId: string;
}
/**
 * @generated from protobuf message chatnow.message.SystemNoticeContent
 */
export interface SystemNoticeContent {
    /**
     * @generated from protobuf field: string text = 1
     */
    text: string;
    /**
     * @generated from protobuf field: string notice_type = 2
     */
    noticeType: string;
}
/**
 * @generated from protobuf message chatnow.message.MessageContent
 */
export interface MessageContent {
    /**
     * @generated from protobuf field: chatnow.message.MessageType type = 1
     */
    type: MessageType;
    /**
     * @generated from protobuf oneof: body
     */
    body: {
        oneofKind: "text";
        /**
         * @generated from protobuf field: chatnow.message.TextContent text = 2
         */
        text: TextContent;
    } | {
        oneofKind: "image";
        /**
         * @generated from protobuf field: chatnow.message.ImageContent image = 3
         */
        image: ImageContent;
    } | {
        oneofKind: "file";
        /**
         * @generated from protobuf field: chatnow.message.FileContent file = 4
         */
        file: FileContent;
    } | {
        oneofKind: "audio";
        /**
         * @generated from protobuf field: chatnow.message.AudioContent audio = 5
         */
        audio: AudioContent;
    } | {
        oneofKind: "video";
        /**
         * @generated from protobuf field: chatnow.message.VideoContent video = 6
         */
        video: VideoContent;
    } | {
        oneofKind: "location";
        /**
         * @generated from protobuf field: chatnow.message.LocationContent location = 7
         */
        location: LocationContent;
    } | {
        oneofKind: "sticker";
        /**
         * @generated from protobuf field: chatnow.message.StickerContent sticker = 8
         */
        sticker: StickerContent;
    } | {
        oneofKind: "notice";
        /**
         * @generated from protobuf field: chatnow.message.SystemNoticeContent notice = 9
         */
        notice: SystemNoticeContent;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message chatnow.message.Message
 */
export interface Message {
    /**
     * @generated from protobuf field: int64 message_id = 1
     */
    messageId: bigint;
    /**
     * @generated from protobuf field: string conversation_id = 2
     */
    conversationId: string;
    /**
     * @generated from protobuf field: chatnow.message.MessageContent content = 3
     */
    content?: MessageContent;
    /**
     * @generated from protobuf field: string sender_id = 4
     */
    senderId: string;
    /**
     * @generated from protobuf field: int64 created_at_ms = 5
     */
    createdAtMs: bigint;
    /**
     * @generated from protobuf field: int64 edited_at_ms = 6
     */
    editedAtMs: bigint;
    /**
     * @generated from protobuf field: uint64 seq_id = 7
     */
    seqId: bigint;
    /**
     * @generated from protobuf field: uint64 user_seq = 8
     */
    userSeq: bigint;
    /**
     * @generated from protobuf field: string client_msg_id = 9
     */
    clientMsgId: string;
    /**
     * @generated from protobuf field: chatnow.message.MessageStatus status = 10
     */
    status: MessageStatus;
    /**
     * @generated from protobuf field: optional chatnow.message.ReplyRef reply_to = 11
     */
    replyTo?: ReplyRef;
    /**
     * @generated from protobuf field: repeated string mentioned_user_ids = 12
     */
    mentionedUserIds: string[];
    /**
     * @generated from protobuf field: optional chatnow.message.ForwardInfo forward_info = 13
     */
    forwardInfo?: ForwardInfo;
    /**
     * @generated from protobuf field: repeated chatnow.message.ReactionGroup reactions = 14
     */
    reactions: ReactionGroup[];
    /**
     * @generated from protobuf field: bool is_pinned = 15
     */
    isPinned: boolean;
}
/**
 * @generated from protobuf message chatnow.message.ReplyRef
 */
export interface ReplyRef {
    /**
     * @generated from protobuf field: int64 replied_message_id = 1
     */
    repliedMessageId: bigint;
    /**
     * @generated from protobuf field: string replied_sender_id = 2
     */
    repliedSenderId: string;
    /**
     * @generated from protobuf field: chatnow.message.MessageType replied_message_type = 3
     */
    repliedMessageType: MessageType;
    /**
     * @generated from protobuf field: string content_preview = 4
     */
    contentPreview: string;
    /**
     * @generated from protobuf field: bool is_recalled = 5
     */
    isRecalled: boolean;
}
/**
 * @generated from protobuf message chatnow.message.ReactionGroup
 */
export interface ReactionGroup {
    /**
     * @generated from protobuf field: string emoji = 1
     */
    emoji: string;
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
    /**
     * @generated from protobuf field: repeated string recent_user_ids = 3
     */
    recentUserIds: string[];
    /**
     * @generated from protobuf field: bool self_reacted = 4
     */
    selfReacted: boolean;
}
/**
 * @generated from protobuf message chatnow.message.ForwardInfo
 */
export interface ForwardInfo {
    /**
     * @generated from protobuf field: string forward_from_user_id = 1
     */
    forwardFromUserId: string;
    /**
     * @generated from protobuf field: int64 forward_at_ms = 2
     */
    forwardAtMs: bigint;
    /**
     * @generated from protobuf field: string source_conversation_id = 3
     */
    sourceConversationId: string;
}
/**
 * @generated from protobuf message chatnow.message.MessagePreview
 */
export interface MessagePreview {
    /**
     * @generated from protobuf field: int64 message_id = 1
     */
    messageId: bigint;
    /**
     * @generated from protobuf field: string sender_id = 2
     */
    senderId: string;
    /**
     * @generated from protobuf field: chatnow.message.MessageType message_type = 3
     */
    messageType: MessageType;
    /**
     * @generated from protobuf field: string content_preview = 4
     */
    contentPreview: string;
    /**
     * @generated from protobuf field: int64 sent_at_ms = 5
     */
    sentAtMs: bigint;
    /**
     * @generated from protobuf field: chatnow.message.MessageStatus status = 6
     */
    status: MessageStatus;
}
/**
 * @generated from protobuf enum chatnow.message.MessageType
 */
export enum MessageType {
    /**
     * @generated from protobuf enum value: MESSAGE_TYPE_UNSPECIFIED = 0;
     */
    MESSAGE_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TEXT = 1;
     */
    TEXT = 1,
    /**
     * @generated from protobuf enum value: IMAGE = 2;
     */
    IMAGE = 2,
    /**
     * @generated from protobuf enum value: FILE = 3;
     */
    FILE = 3,
    /**
     * @generated from protobuf enum value: AUDIO = 4;
     */
    AUDIO = 4,
    /**
     * @generated from protobuf enum value: VIDEO = 5;
     */
    VIDEO = 5,
    /**
     * @generated from protobuf enum value: LOCATION = 6;
     */
    LOCATION = 6,
    /**
     * @generated from protobuf enum value: STICKER = 7;
     */
    STICKER = 7,
    /**
     * @generated from protobuf enum value: SYSTEM_NOTICE = 8;
     */
    SYSTEM_NOTICE = 8
}
/**
 * @generated from protobuf enum chatnow.message.MessageStatus
 */
export enum MessageStatus {
    /**
     * @generated from protobuf enum value: MESSAGE_STATUS_NORMAL = 0;
     */
    NORMAL = 0,
    /**
     * @generated from protobuf enum value: MESSAGE_STATUS_RECALLED = 1;
     */
    RECALLED = 1,
    /**
     * @generated from protobuf enum value: MESSAGE_STATUS_DELETED = 2;
     */
    DELETED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class TextContent$Type extends MessageType$<TextContent> {
    constructor() {
        super("chatnow.message.TextContent", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TextContent>): TextContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<TextContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextContent): TextContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TextContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.TextContent
 */
export const TextContent = new TextContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImageContent$Type extends MessageType$<ImageContent> {
    constructor() {
        super("chatnow.message.ImageContent", [
            { no: 1, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "thumbnail_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ImageContent>): ImageContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.width = 0;
        message.height = 0;
        message.thumbnailUrl = "";
        if (value !== undefined)
            reflectionMergePartial<ImageContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImageContent): ImageContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file_id */ 1:
                    message.fileId = reader.string();
                    break;
                case /* int32 width */ 2:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 3:
                    message.height = reader.int32();
                    break;
                case /* string thumbnail_url */ 4:
                    message.thumbnailUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImageContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file_id = 1; */
        if (message.fileId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fileId);
        /* int32 width = 2; */
        if (message.width !== 0)
            writer.tag(2, WireType.Varint).int32(message.width);
        /* int32 height = 3; */
        if (message.height !== 0)
            writer.tag(3, WireType.Varint).int32(message.height);
        /* string thumbnail_url = 4; */
        if (message.thumbnailUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.thumbnailUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.ImageContent
 */
export const ImageContent = new ImageContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FileContent$Type extends MessageType$<FileContent> {
    constructor() {
        super("chatnow.message.FileContent", [
            { no: 1, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "file_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 4, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FileContent>): FileContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.fileName = "";
        message.fileSize = 0n;
        message.mimeType = "";
        if (value !== undefined)
            reflectionMergePartial<FileContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FileContent): FileContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file_id */ 1:
                    message.fileId = reader.string();
                    break;
                case /* string file_name */ 2:
                    message.fileName = reader.string();
                    break;
                case /* int64 file_size */ 3:
                    message.fileSize = reader.int64().toBigInt();
                    break;
                case /* string mime_type */ 4:
                    message.mimeType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FileContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file_id = 1; */
        if (message.fileId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fileId);
        /* string file_name = 2; */
        if (message.fileName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.fileName);
        /* int64 file_size = 3; */
        if (message.fileSize !== 0n)
            writer.tag(3, WireType.Varint).int64(message.fileSize);
        /* string mime_type = 4; */
        if (message.mimeType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.mimeType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.FileContent
 */
export const FileContent = new FileContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AudioContent$Type extends MessageType$<AudioContent> {
    constructor() {
        super("chatnow.message.AudioContent", [
            { no: 1, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "duration_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<AudioContent>): AudioContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.durationSec = 0;
        if (value !== undefined)
            reflectionMergePartial<AudioContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AudioContent): AudioContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file_id */ 1:
                    message.fileId = reader.string();
                    break;
                case /* int32 duration_sec */ 2:
                    message.durationSec = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AudioContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file_id = 1; */
        if (message.fileId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fileId);
        /* int32 duration_sec = 2; */
        if (message.durationSec !== 0)
            writer.tag(2, WireType.Varint).int32(message.durationSec);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.AudioContent
 */
export const AudioContent = new AudioContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VideoContent$Type extends MessageType$<VideoContent> {
    constructor() {
        super("chatnow.message.VideoContent", [
            { no: 1, name: "file_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "duration_sec", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "thumbnail_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<VideoContent>): VideoContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fileId = "";
        message.durationSec = 0;
        message.width = 0;
        message.height = 0;
        message.thumbnailUrl = "";
        if (value !== undefined)
            reflectionMergePartial<VideoContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VideoContent): VideoContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file_id */ 1:
                    message.fileId = reader.string();
                    break;
                case /* int32 duration_sec */ 2:
                    message.durationSec = reader.int32();
                    break;
                case /* int32 width */ 3:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 4:
                    message.height = reader.int32();
                    break;
                case /* string thumbnail_url */ 5:
                    message.thumbnailUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: VideoContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file_id = 1; */
        if (message.fileId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.fileId);
        /* int32 duration_sec = 2; */
        if (message.durationSec !== 0)
            writer.tag(2, WireType.Varint).int32(message.durationSec);
        /* int32 width = 3; */
        if (message.width !== 0)
            writer.tag(3, WireType.Varint).int32(message.width);
        /* int32 height = 4; */
        if (message.height !== 0)
            writer.tag(4, WireType.Varint).int32(message.height);
        /* string thumbnail_url = 5; */
        if (message.thumbnailUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.thumbnailUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.VideoContent
 */
export const VideoContent = new VideoContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocationContent$Type extends MessageType$<LocationContent> {
    constructor() {
        super("chatnow.message.LocationContent", [
            { no: 1, name: "latitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "longitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocationContent>): LocationContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.latitude = 0;
        message.longitude = 0;
        message.name = "";
        message.address = "";
        if (value !== undefined)
            reflectionMergePartial<LocationContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocationContent): LocationContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double latitude */ 1:
                    message.latitude = reader.double();
                    break;
                case /* double longitude */ 2:
                    message.longitude = reader.double();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string address */ 4:
                    message.address = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocationContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double latitude = 1; */
        if (message.latitude !== 0)
            writer.tag(1, WireType.Bit64).double(message.latitude);
        /* double longitude = 2; */
        if (message.longitude !== 0)
            writer.tag(2, WireType.Bit64).double(message.longitude);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string address = 4; */
        if (message.address !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.address);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.LocationContent
 */
export const LocationContent = new LocationContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StickerContent$Type extends MessageType$<StickerContent> {
    constructor() {
        super("chatnow.message.StickerContent", [
            { no: 1, name: "sticker_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "pack_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StickerContent>): StickerContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.stickerId = "";
        message.packId = "";
        if (value !== undefined)
            reflectionMergePartial<StickerContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StickerContent): StickerContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string sticker_id */ 1:
                    message.stickerId = reader.string();
                    break;
                case /* string pack_id */ 2:
                    message.packId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StickerContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string sticker_id = 1; */
        if (message.stickerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.stickerId);
        /* string pack_id = 2; */
        if (message.packId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.packId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.StickerContent
 */
export const StickerContent = new StickerContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SystemNoticeContent$Type extends MessageType$<SystemNoticeContent> {
    constructor() {
        super("chatnow.message.SystemNoticeContent", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "notice_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SystemNoticeContent>): SystemNoticeContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        message.noticeType = "";
        if (value !== undefined)
            reflectionMergePartial<SystemNoticeContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SystemNoticeContent): SystemNoticeContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* string notice_type */ 2:
                    message.noticeType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SystemNoticeContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* string notice_type = 2; */
        if (message.noticeType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.noticeType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.SystemNoticeContent
 */
export const SystemNoticeContent = new SystemNoticeContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MessageContent$Type extends MessageType$<MessageContent> {
    constructor() {
        super("chatnow.message.MessageContent", [
            { no: 1, name: "type", kind: "enum", T: () => ["chatnow.message.MessageType", MessageType] },
            { no: 2, name: "text", kind: "message", oneof: "body", T: () => TextContent },
            { no: 3, name: "image", kind: "message", oneof: "body", T: () => ImageContent },
            { no: 4, name: "file", kind: "message", oneof: "body", T: () => FileContent },
            { no: 5, name: "audio", kind: "message", oneof: "body", T: () => AudioContent },
            { no: 6, name: "video", kind: "message", oneof: "body", T: () => VideoContent },
            { no: 7, name: "location", kind: "message", oneof: "body", T: () => LocationContent },
            { no: 8, name: "sticker", kind: "message", oneof: "body", T: () => StickerContent },
            { no: 9, name: "notice", kind: "message", oneof: "body", T: () => SystemNoticeContent }
        ]);
    }
    create(value?: PartialMessage<MessageContent>): MessageContent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.body = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<MessageContent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MessageContent): MessageContent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.message.MessageType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* chatnow.message.TextContent text */ 2:
                    message.body = {
                        oneofKind: "text",
                        text: TextContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).text)
                    };
                    break;
                case /* chatnow.message.ImageContent image */ 3:
                    message.body = {
                        oneofKind: "image",
                        image: ImageContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).image)
                    };
                    break;
                case /* chatnow.message.FileContent file */ 4:
                    message.body = {
                        oneofKind: "file",
                        file: FileContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).file)
                    };
                    break;
                case /* chatnow.message.AudioContent audio */ 5:
                    message.body = {
                        oneofKind: "audio",
                        audio: AudioContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).audio)
                    };
                    break;
                case /* chatnow.message.VideoContent video */ 6:
                    message.body = {
                        oneofKind: "video",
                        video: VideoContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).video)
                    };
                    break;
                case /* chatnow.message.LocationContent location */ 7:
                    message.body = {
                        oneofKind: "location",
                        location: LocationContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).location)
                    };
                    break;
                case /* chatnow.message.StickerContent sticker */ 8:
                    message.body = {
                        oneofKind: "sticker",
                        sticker: StickerContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).sticker)
                    };
                    break;
                case /* chatnow.message.SystemNoticeContent notice */ 9:
                    message.body = {
                        oneofKind: "notice",
                        notice: SystemNoticeContent.internalBinaryRead(reader, reader.uint32(), options, (message.body as any).notice)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MessageContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.message.MessageType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* chatnow.message.TextContent text = 2; */
        if (message.body.oneofKind === "text")
            TextContent.internalBinaryWrite(message.body.text, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.ImageContent image = 3; */
        if (message.body.oneofKind === "image")
            ImageContent.internalBinaryWrite(message.body.image, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.FileContent file = 4; */
        if (message.body.oneofKind === "file")
            FileContent.internalBinaryWrite(message.body.file, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.AudioContent audio = 5; */
        if (message.body.oneofKind === "audio")
            AudioContent.internalBinaryWrite(message.body.audio, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.VideoContent video = 6; */
        if (message.body.oneofKind === "video")
            VideoContent.internalBinaryWrite(message.body.video, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.LocationContent location = 7; */
        if (message.body.oneofKind === "location")
            LocationContent.internalBinaryWrite(message.body.location, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.StickerContent sticker = 8; */
        if (message.body.oneofKind === "sticker")
            StickerContent.internalBinaryWrite(message.body.sticker, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.SystemNoticeContent notice = 9; */
        if (message.body.oneofKind === "notice")
            SystemNoticeContent.internalBinaryWrite(message.body.notice, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.MessageContent
 */
export const MessageContent = new MessageContent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Message$Type extends MessageType$<Message> {
    constructor() {
        super("chatnow.message.Message", [
            { no: 1, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "message", T: () => MessageContent },
            { no: 4, name: "sender_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "edited_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "seq_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "user_seq", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 9, name: "client_msg_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "status", kind: "enum", T: () => ["chatnow.message.MessageStatus", MessageStatus, "MESSAGE_STATUS_"] },
            { no: 11, name: "reply_to", kind: "message", T: () => ReplyRef },
            { no: 12, name: "mentioned_user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "forward_info", kind: "message", T: () => ForwardInfo },
            { no: 14, name: "reactions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ReactionGroup },
            { no: 15, name: "is_pinned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Message>): Message {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messageId = 0n;
        message.conversationId = "";
        message.senderId = "";
        message.createdAtMs = 0n;
        message.editedAtMs = 0n;
        message.seqId = 0n;
        message.userSeq = 0n;
        message.clientMsgId = "";
        message.status = 0;
        message.mentionedUserIds = [];
        message.reactions = [];
        message.isPinned = false;
        if (value !== undefined)
            reflectionMergePartial<Message>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Message): Message {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 message_id */ 1:
                    message.messageId = reader.int64().toBigInt();
                    break;
                case /* string conversation_id */ 2:
                    message.conversationId = reader.string();
                    break;
                case /* chatnow.message.MessageContent content */ 3:
                    message.content = MessageContent.internalBinaryRead(reader, reader.uint32(), options, message.content);
                    break;
                case /* string sender_id */ 4:
                    message.senderId = reader.string();
                    break;
                case /* int64 created_at_ms */ 5:
                    message.createdAtMs = reader.int64().toBigInt();
                    break;
                case /* int64 edited_at_ms */ 6:
                    message.editedAtMs = reader.int64().toBigInt();
                    break;
                case /* uint64 seq_id */ 7:
                    message.seqId = reader.uint64().toBigInt();
                    break;
                case /* uint64 user_seq */ 8:
                    message.userSeq = reader.uint64().toBigInt();
                    break;
                case /* string client_msg_id */ 9:
                    message.clientMsgId = reader.string();
                    break;
                case /* chatnow.message.MessageStatus status */ 10:
                    message.status = reader.int32();
                    break;
                case /* optional chatnow.message.ReplyRef reply_to */ 11:
                    message.replyTo = ReplyRef.internalBinaryRead(reader, reader.uint32(), options, message.replyTo);
                    break;
                case /* repeated string mentioned_user_ids */ 12:
                    message.mentionedUserIds.push(reader.string());
                    break;
                case /* optional chatnow.message.ForwardInfo forward_info */ 13:
                    message.forwardInfo = ForwardInfo.internalBinaryRead(reader, reader.uint32(), options, message.forwardInfo);
                    break;
                case /* repeated chatnow.message.ReactionGroup reactions */ 14:
                    message.reactions.push(ReactionGroup.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool is_pinned */ 15:
                    message.isPinned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Message, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 message_id = 1; */
        if (message.messageId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.messageId);
        /* string conversation_id = 2; */
        if (message.conversationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationId);
        /* chatnow.message.MessageContent content = 3; */
        if (message.content)
            MessageContent.internalBinaryWrite(message.content, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string sender_id = 4; */
        if (message.senderId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.senderId);
        /* int64 created_at_ms = 5; */
        if (message.createdAtMs !== 0n)
            writer.tag(5, WireType.Varint).int64(message.createdAtMs);
        /* int64 edited_at_ms = 6; */
        if (message.editedAtMs !== 0n)
            writer.tag(6, WireType.Varint).int64(message.editedAtMs);
        /* uint64 seq_id = 7; */
        if (message.seqId !== 0n)
            writer.tag(7, WireType.Varint).uint64(message.seqId);
        /* uint64 user_seq = 8; */
        if (message.userSeq !== 0n)
            writer.tag(8, WireType.Varint).uint64(message.userSeq);
        /* string client_msg_id = 9; */
        if (message.clientMsgId !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.clientMsgId);
        /* chatnow.message.MessageStatus status = 10; */
        if (message.status !== 0)
            writer.tag(10, WireType.Varint).int32(message.status);
        /* optional chatnow.message.ReplyRef reply_to = 11; */
        if (message.replyTo)
            ReplyRef.internalBinaryWrite(message.replyTo, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* repeated string mentioned_user_ids = 12; */
        for (let i = 0; i < message.mentionedUserIds.length; i++)
            writer.tag(12, WireType.LengthDelimited).string(message.mentionedUserIds[i]);
        /* optional chatnow.message.ForwardInfo forward_info = 13; */
        if (message.forwardInfo)
            ForwardInfo.internalBinaryWrite(message.forwardInfo, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* repeated chatnow.message.ReactionGroup reactions = 14; */
        for (let i = 0; i < message.reactions.length; i++)
            ReactionGroup.internalBinaryWrite(message.reactions[i], writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* bool is_pinned = 15; */
        if (message.isPinned !== false)
            writer.tag(15, WireType.Varint).bool(message.isPinned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.Message
 */
export const Message = new Message$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReplyRef$Type extends MessageType$<ReplyRef> {
    constructor() {
        super("chatnow.message.ReplyRef", [
            { no: 1, name: "replied_message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "replied_sender_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "replied_message_type", kind: "enum", T: () => ["chatnow.message.MessageType", MessageType] },
            { no: 4, name: "content_preview", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "is_recalled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ReplyRef>): ReplyRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.repliedMessageId = 0n;
        message.repliedSenderId = "";
        message.repliedMessageType = 0;
        message.contentPreview = "";
        message.isRecalled = false;
        if (value !== undefined)
            reflectionMergePartial<ReplyRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReplyRef): ReplyRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 replied_message_id */ 1:
                    message.repliedMessageId = reader.int64().toBigInt();
                    break;
                case /* string replied_sender_id */ 2:
                    message.repliedSenderId = reader.string();
                    break;
                case /* chatnow.message.MessageType replied_message_type */ 3:
                    message.repliedMessageType = reader.int32();
                    break;
                case /* string content_preview */ 4:
                    message.contentPreview = reader.string();
                    break;
                case /* bool is_recalled */ 5:
                    message.isRecalled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReplyRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 replied_message_id = 1; */
        if (message.repliedMessageId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.repliedMessageId);
        /* string replied_sender_id = 2; */
        if (message.repliedSenderId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.repliedSenderId);
        /* chatnow.message.MessageType replied_message_type = 3; */
        if (message.repliedMessageType !== 0)
            writer.tag(3, WireType.Varint).int32(message.repliedMessageType);
        /* string content_preview = 4; */
        if (message.contentPreview !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.contentPreview);
        /* bool is_recalled = 5; */
        if (message.isRecalled !== false)
            writer.tag(5, WireType.Varint).bool(message.isRecalled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.ReplyRef
 */
export const ReplyRef = new ReplyRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReactionGroup$Type extends MessageType$<ReactionGroup> {
    constructor() {
        super("chatnow.message.ReactionGroup", [
            { no: 1, name: "emoji", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "recent_user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "self_reacted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ReactionGroup>): ReactionGroup {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.emoji = "";
        message.count = 0;
        message.recentUserIds = [];
        message.selfReacted = false;
        if (value !== undefined)
            reflectionMergePartial<ReactionGroup>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReactionGroup): ReactionGroup {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string emoji */ 1:
                    message.emoji = reader.string();
                    break;
                case /* int32 count */ 2:
                    message.count = reader.int32();
                    break;
                case /* repeated string recent_user_ids */ 3:
                    message.recentUserIds.push(reader.string());
                    break;
                case /* bool self_reacted */ 4:
                    message.selfReacted = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReactionGroup, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string emoji = 1; */
        if (message.emoji !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.emoji);
        /* int32 count = 2; */
        if (message.count !== 0)
            writer.tag(2, WireType.Varint).int32(message.count);
        /* repeated string recent_user_ids = 3; */
        for (let i = 0; i < message.recentUserIds.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.recentUserIds[i]);
        /* bool self_reacted = 4; */
        if (message.selfReacted !== false)
            writer.tag(4, WireType.Varint).bool(message.selfReacted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.ReactionGroup
 */
export const ReactionGroup = new ReactionGroup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ForwardInfo$Type extends MessageType$<ForwardInfo> {
    constructor() {
        super("chatnow.message.ForwardInfo", [
            { no: 1, name: "forward_from_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "forward_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "source_conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ForwardInfo>): ForwardInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.forwardFromUserId = "";
        message.forwardAtMs = 0n;
        message.sourceConversationId = "";
        if (value !== undefined)
            reflectionMergePartial<ForwardInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ForwardInfo): ForwardInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string forward_from_user_id */ 1:
                    message.forwardFromUserId = reader.string();
                    break;
                case /* int64 forward_at_ms */ 2:
                    message.forwardAtMs = reader.int64().toBigInt();
                    break;
                case /* string source_conversation_id */ 3:
                    message.sourceConversationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ForwardInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string forward_from_user_id = 1; */
        if (message.forwardFromUserId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.forwardFromUserId);
        /* int64 forward_at_ms = 2; */
        if (message.forwardAtMs !== 0n)
            writer.tag(2, WireType.Varint).int64(message.forwardAtMs);
        /* string source_conversation_id = 3; */
        if (message.sourceConversationId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.sourceConversationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.ForwardInfo
 */
export const ForwardInfo = new ForwardInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MessagePreview$Type extends MessageType$<MessagePreview> {
    constructor() {
        super("chatnow.message.MessagePreview", [
            { no: 1, name: "message_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "sender_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message_type", kind: "enum", T: () => ["chatnow.message.MessageType", MessageType] },
            { no: 4, name: "content_preview", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "sent_at_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "status", kind: "enum", T: () => ["chatnow.message.MessageStatus", MessageStatus, "MESSAGE_STATUS_"] }
        ]);
    }
    create(value?: PartialMessage<MessagePreview>): MessagePreview {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messageId = 0n;
        message.senderId = "";
        message.messageType = 0;
        message.contentPreview = "";
        message.sentAtMs = 0n;
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<MessagePreview>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MessagePreview): MessagePreview {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 message_id */ 1:
                    message.messageId = reader.int64().toBigInt();
                    break;
                case /* string sender_id */ 2:
                    message.senderId = reader.string();
                    break;
                case /* chatnow.message.MessageType message_type */ 3:
                    message.messageType = reader.int32();
                    break;
                case /* string content_preview */ 4:
                    message.contentPreview = reader.string();
                    break;
                case /* int64 sent_at_ms */ 5:
                    message.sentAtMs = reader.int64().toBigInt();
                    break;
                case /* chatnow.message.MessageStatus status */ 6:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MessagePreview, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 message_id = 1; */
        if (message.messageId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.messageId);
        /* string sender_id = 2; */
        if (message.senderId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.senderId);
        /* chatnow.message.MessageType message_type = 3; */
        if (message.messageType !== 0)
            writer.tag(3, WireType.Varint).int32(message.messageType);
        /* string content_preview = 4; */
        if (message.contentPreview !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.contentPreview);
        /* int64 sent_at_ms = 5; */
        if (message.sentAtMs !== 0n)
            writer.tag(5, WireType.Varint).int64(message.sentAtMs);
        /* chatnow.message.MessageStatus status = 6; */
        if (message.status !== 0)
            writer.tag(6, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.message.MessagePreview
 */
export const MessagePreview = new MessagePreview$Type();
