// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "relationship/relationship_service.proto" (package "chatnow.relationship", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RelationshipService } from "./relationship_service";
import type { ListPendingRsp } from "./relationship_service";
import type { ListPendingReq } from "./relationship_service";
import type { ListBlockedRsp } from "./relationship_service";
import type { ListBlockedReq } from "./relationship_service";
import type { UnblockUserRsp } from "./relationship_service";
import type { UnblockUserReq } from "./relationship_service";
import type { BlockUserRsp } from "./relationship_service";
import type { BlockUserReq } from "./relationship_service";
import type { SearchFriendsRsp } from "./relationship_service";
import type { SearchFriendsReq } from "./relationship_service";
import type { RemoveFriendRsp } from "./relationship_service";
import type { RemoveFriendReq } from "./relationship_service";
import type { HandleFriendRsp } from "./relationship_service";
import type { HandleFriendReq } from "./relationship_service";
import type { SendFriendRsp } from "./relationship_service";
import type { SendFriendReq } from "./relationship_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListFriendsRsp } from "./relationship_service";
import type { ListFriendsReq } from "./relationship_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.relationship.RelationshipService
 */
export interface IRelationshipServiceClient {
    /**
     * @generated from protobuf rpc: ListFriends
     */
    listFriends(input: ListFriendsReq, options?: RpcOptions): UnaryCall<ListFriendsReq, ListFriendsRsp>;
    /**
     * @generated from protobuf rpc: SendFriendRequest
     */
    sendFriendRequest(input: SendFriendReq, options?: RpcOptions): UnaryCall<SendFriendReq, SendFriendRsp>;
    /**
     * @generated from protobuf rpc: HandleFriendRequest
     */
    handleFriendRequest(input: HandleFriendReq, options?: RpcOptions): UnaryCall<HandleFriendReq, HandleFriendRsp>;
    /**
     * @generated from protobuf rpc: RemoveFriend
     */
    removeFriend(input: RemoveFriendReq, options?: RpcOptions): UnaryCall<RemoveFriendReq, RemoveFriendRsp>;
    /**
     * @generated from protobuf rpc: SearchFriends
     */
    searchFriends(input: SearchFriendsReq, options?: RpcOptions): UnaryCall<SearchFriendsReq, SearchFriendsRsp>;
    /**
     * @generated from protobuf rpc: BlockUser
     */
    blockUser(input: BlockUserReq, options?: RpcOptions): UnaryCall<BlockUserReq, BlockUserRsp>;
    /**
     * @generated from protobuf rpc: UnblockUser
     */
    unblockUser(input: UnblockUserReq, options?: RpcOptions): UnaryCall<UnblockUserReq, UnblockUserRsp>;
    /**
     * @generated from protobuf rpc: ListBlockedUsers
     */
    listBlockedUsers(input: ListBlockedReq, options?: RpcOptions): UnaryCall<ListBlockedReq, ListBlockedRsp>;
    /**
     * @generated from protobuf rpc: ListPendingRequests
     */
    listPendingRequests(input: ListPendingReq, options?: RpcOptions): UnaryCall<ListPendingReq, ListPendingRsp>;
}
/**
 * @generated from protobuf service chatnow.relationship.RelationshipService
 */
export class RelationshipServiceClient implements IRelationshipServiceClient, ServiceInfo {
    typeName = RelationshipService.typeName;
    methods = RelationshipService.methods;
    options = RelationshipService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListFriends
     */
    listFriends(input: ListFriendsReq, options?: RpcOptions): UnaryCall<ListFriendsReq, ListFriendsRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListFriendsReq, ListFriendsRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SendFriendRequest
     */
    sendFriendRequest(input: SendFriendReq, options?: RpcOptions): UnaryCall<SendFriendReq, SendFriendRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendFriendReq, SendFriendRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: HandleFriendRequest
     */
    handleFriendRequest(input: HandleFriendReq, options?: RpcOptions): UnaryCall<HandleFriendReq, HandleFriendRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<HandleFriendReq, HandleFriendRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveFriend
     */
    removeFriend(input: RemoveFriendReq, options?: RpcOptions): UnaryCall<RemoveFriendReq, RemoveFriendRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveFriendReq, RemoveFriendRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchFriends
     */
    searchFriends(input: SearchFriendsReq, options?: RpcOptions): UnaryCall<SearchFriendsReq, SearchFriendsRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchFriendsReq, SearchFriendsRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BlockUser
     */
    blockUser(input: BlockUserReq, options?: RpcOptions): UnaryCall<BlockUserReq, BlockUserRsp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlockUserReq, BlockUserRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnblockUser
     */
    unblockUser(input: UnblockUserReq, options?: RpcOptions): UnaryCall<UnblockUserReq, UnblockUserRsp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnblockUserReq, UnblockUserRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBlockedUsers
     */
    listBlockedUsers(input: ListBlockedReq, options?: RpcOptions): UnaryCall<ListBlockedReq, ListBlockedRsp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBlockedReq, ListBlockedRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPendingRequests
     */
    listPendingRequests(input: ListPendingReq, options?: RpcOptions): UnaryCall<ListPendingReq, ListPendingRsp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPendingReq, ListPendingRsp>("unary", this._transport, method, opt, input);
    }
}
