// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "conversation/conversation_service.proto" (package "chatnow.conversation", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ConversationService } from "./conversation_service";
import type { GetMemberIdsRsp } from "./conversation_service";
import type { GetMemberIdsReq } from "./conversation_service";
import type { SearchConversationsRsp } from "./conversation_service";
import type { SearchConversationsReq } from "./conversation_service";
import type { SaveDraftRsp } from "./conversation_service";
import type { SaveDraftReq } from "./conversation_service";
import type { MarkReadRsp } from "./conversation_service";
import type { MarkReadReq } from "./conversation_service";
import type { QuitConversationRsp } from "./conversation_service";
import type { QuitConversationReq } from "./conversation_service";
import type { SetVisibleRsp } from "./conversation_service";
import type { SetVisibleReq } from "./conversation_service";
import type { SetPinRsp } from "./conversation_service";
import type { SetPinReq } from "./conversation_service";
import type { SetMuteRsp } from "./conversation_service";
import type { SetMuteReq } from "./conversation_service";
import type { ListMembersRsp } from "./conversation_service";
import type { ListMembersReq } from "./conversation_service";
import type { ChangeMemberRoleRsp } from "./conversation_service";
import type { ChangeMemberRoleReq } from "./conversation_service";
import type { TransferOwnerRsp } from "./conversation_service";
import type { TransferOwnerReq } from "./conversation_service";
import type { RemoveMembersRsp } from "./conversation_service";
import type { RemoveMembersReq } from "./conversation_service";
import type { AddMembersRsp } from "./conversation_service";
import type { AddMembersReq } from "./conversation_service";
import type { DismissConversationRsp } from "./conversation_service";
import type { DismissConversationReq } from "./conversation_service";
import type { UpdateConversationRsp } from "./conversation_service";
import type { UpdateConversationReq } from "./conversation_service";
import type { CreateConversationRsp } from "./conversation_service";
import type { CreateConversationReq } from "./conversation_service";
import type { GetConversationRsp } from "./conversation_service";
import type { GetConversationReq } from "./conversation_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ListConversationsRsp } from "./conversation_service";
import type { ListConversationsReq } from "./conversation_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.conversation.ConversationService
 */
export interface IConversationServiceClient {
    /**
     * @generated from protobuf rpc: ListConversations
     */
    listConversations(input: ListConversationsReq, options?: RpcOptions): UnaryCall<ListConversationsReq, ListConversationsRsp>;
    /**
     * @generated from protobuf rpc: GetConversation
     */
    getConversation(input: GetConversationReq, options?: RpcOptions): UnaryCall<GetConversationReq, GetConversationRsp>;
    /**
     * @generated from protobuf rpc: CreateConversation
     */
    createConversation(input: CreateConversationReq, options?: RpcOptions): UnaryCall<CreateConversationReq, CreateConversationRsp>;
    /**
     * @generated from protobuf rpc: UpdateConversation
     */
    updateConversation(input: UpdateConversationReq, options?: RpcOptions): UnaryCall<UpdateConversationReq, UpdateConversationRsp>;
    /**
     * @generated from protobuf rpc: DismissConversation
     */
    dismissConversation(input: DismissConversationReq, options?: RpcOptions): UnaryCall<DismissConversationReq, DismissConversationRsp>;
    /**
     * @generated from protobuf rpc: AddMembers
     */
    addMembers(input: AddMembersReq, options?: RpcOptions): UnaryCall<AddMembersReq, AddMembersRsp>;
    /**
     * @generated from protobuf rpc: RemoveMembers
     */
    removeMembers(input: RemoveMembersReq, options?: RpcOptions): UnaryCall<RemoveMembersReq, RemoveMembersRsp>;
    /**
     * @generated from protobuf rpc: TransferOwner
     */
    transferOwner(input: TransferOwnerReq, options?: RpcOptions): UnaryCall<TransferOwnerReq, TransferOwnerRsp>;
    /**
     * @generated from protobuf rpc: ChangeMemberRole
     */
    changeMemberRole(input: ChangeMemberRoleReq, options?: RpcOptions): UnaryCall<ChangeMemberRoleReq, ChangeMemberRoleRsp>;
    /**
     * @generated from protobuf rpc: ListMembers
     */
    listMembers(input: ListMembersReq, options?: RpcOptions): UnaryCall<ListMembersReq, ListMembersRsp>;
    /**
     * @generated from protobuf rpc: SetMute
     */
    setMute(input: SetMuteReq, options?: RpcOptions): UnaryCall<SetMuteReq, SetMuteRsp>;
    /**
     * @generated from protobuf rpc: SetPin
     */
    setPin(input: SetPinReq, options?: RpcOptions): UnaryCall<SetPinReq, SetPinRsp>;
    /**
     * @generated from protobuf rpc: SetVisible
     */
    setVisible(input: SetVisibleReq, options?: RpcOptions): UnaryCall<SetVisibleReq, SetVisibleRsp>;
    /**
     * @generated from protobuf rpc: QuitConversation
     */
    quitConversation(input: QuitConversationReq, options?: RpcOptions): UnaryCall<QuitConversationReq, QuitConversationRsp>;
    /**
     * @generated from protobuf rpc: MarkRead
     */
    markRead(input: MarkReadReq, options?: RpcOptions): UnaryCall<MarkReadReq, MarkReadRsp>;
    /**
     * @generated from protobuf rpc: SaveDraft
     */
    saveDraft(input: SaveDraftReq, options?: RpcOptions): UnaryCall<SaveDraftReq, SaveDraftRsp>;
    /**
     * @generated from protobuf rpc: SearchConversations
     */
    searchConversations(input: SearchConversationsReq, options?: RpcOptions): UnaryCall<SearchConversationsReq, SearchConversationsRsp>;
    /**
     * @generated from protobuf rpc: GetMemberIds
     */
    getMemberIds(input: GetMemberIdsReq, options?: RpcOptions): UnaryCall<GetMemberIdsReq, GetMemberIdsRsp>;
}
/**
 * @generated from protobuf service chatnow.conversation.ConversationService
 */
export class ConversationServiceClient implements IConversationServiceClient, ServiceInfo {
    typeName = ConversationService.typeName;
    methods = ConversationService.methods;
    options = ConversationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListConversations
     */
    listConversations(input: ListConversationsReq, options?: RpcOptions): UnaryCall<ListConversationsReq, ListConversationsRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListConversationsReq, ListConversationsRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetConversation
     */
    getConversation(input: GetConversationReq, options?: RpcOptions): UnaryCall<GetConversationReq, GetConversationRsp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetConversationReq, GetConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateConversation
     */
    createConversation(input: CreateConversationReq, options?: RpcOptions): UnaryCall<CreateConversationReq, CreateConversationRsp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateConversationReq, CreateConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConversation
     */
    updateConversation(input: UpdateConversationReq, options?: RpcOptions): UnaryCall<UpdateConversationReq, UpdateConversationRsp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConversationReq, UpdateConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DismissConversation
     */
    dismissConversation(input: DismissConversationReq, options?: RpcOptions): UnaryCall<DismissConversationReq, DismissConversationRsp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DismissConversationReq, DismissConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddMembers
     */
    addMembers(input: AddMembersReq, options?: RpcOptions): UnaryCall<AddMembersReq, AddMembersRsp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddMembersReq, AddMembersRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveMembers
     */
    removeMembers(input: RemoveMembersReq, options?: RpcOptions): UnaryCall<RemoveMembersReq, RemoveMembersRsp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveMembersReq, RemoveMembersRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TransferOwner
     */
    transferOwner(input: TransferOwnerReq, options?: RpcOptions): UnaryCall<TransferOwnerReq, TransferOwnerRsp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<TransferOwnerReq, TransferOwnerRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangeMemberRole
     */
    changeMemberRole(input: ChangeMemberRoleReq, options?: RpcOptions): UnaryCall<ChangeMemberRoleReq, ChangeMemberRoleRsp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangeMemberRoleReq, ChangeMemberRoleRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMembers
     */
    listMembers(input: ListMembersReq, options?: RpcOptions): UnaryCall<ListMembersReq, ListMembersRsp> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMembersReq, ListMembersRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetMute
     */
    setMute(input: SetMuteReq, options?: RpcOptions): UnaryCall<SetMuteReq, SetMuteRsp> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetMuteReq, SetMuteRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetPin
     */
    setPin(input: SetPinReq, options?: RpcOptions): UnaryCall<SetPinReq, SetPinRsp> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetPinReq, SetPinRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetVisible
     */
    setVisible(input: SetVisibleReq, options?: RpcOptions): UnaryCall<SetVisibleReq, SetVisibleRsp> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetVisibleReq, SetVisibleRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: QuitConversation
     */
    quitConversation(input: QuitConversationReq, options?: RpcOptions): UnaryCall<QuitConversationReq, QuitConversationRsp> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<QuitConversationReq, QuitConversationRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkRead
     */
    markRead(input: MarkReadReq, options?: RpcOptions): UnaryCall<MarkReadReq, MarkReadRsp> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<MarkReadReq, MarkReadRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveDraft
     */
    saveDraft(input: SaveDraftReq, options?: RpcOptions): UnaryCall<SaveDraftReq, SaveDraftRsp> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<SaveDraftReq, SaveDraftRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchConversations
     */
    searchConversations(input: SearchConversationsReq, options?: RpcOptions): UnaryCall<SearchConversationsReq, SearchConversationsRsp> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchConversationsReq, SearchConversationsRsp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMemberIds
     */
    getMemberIds(input: GetMemberIdsReq, options?: RpcOptions): UnaryCall<GetMemberIdsReq, GetMemberIdsRsp> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMemberIdsReq, GetMemberIdsRsp>("unary", this._transport, method, opt, input);
    }
}
