// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "transmite/transmite_service.proto" (package "chatnow.transmite", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Message } from "../message/message_types";
import { ResponseHeader } from "../common/envelope";
import { ForwardInfo } from "../message/message_types";
import { ReplyRef } from "../message/message_types";
import { MessageContent } from "../message/message_types";
/**
 * @generated from protobuf message chatnow.transmite.SendMessageReq
 */
export interface SendMessageReq {
    /**
     * @generated from protobuf field: string request_id = 1
     */
    requestId: string;
    /**
     * @generated from protobuf field: string conversation_id = 2
     */
    conversationId: string;
    /**
     * @generated from protobuf field: chatnow.message.MessageContent content = 3
     */
    content?: MessageContent;
    /**
     * @generated from protobuf field: string client_msg_id = 4
     */
    clientMsgId: string; // 客户端幂等键
    /**
     * @generated from protobuf field: optional chatnow.message.ReplyRef reply_to = 5
     */
    replyTo?: ReplyRef; // 回复引用
    /**
     * @generated from protobuf field: repeated string mentioned_user_ids = 6
     */
    mentionedUserIds: string[]; // @提及
    /**
     * @generated from protobuf field: optional chatnow.message.ForwardInfo forward_info = 7
     */
    forwardInfo?: ForwardInfo; // 转发来源
}
/**
 * @generated from protobuf message chatnow.transmite.SendMessageRsp
 */
export interface SendMessageRsp {
    /**
     * @generated from protobuf field: chatnow.common.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * @generated from protobuf field: chatnow.message.Message message = 2
     */
    message?: Message; // 组装后的完整消息
}
// @generated message type with reflection information, may provide speed optimized methods
class SendMessageReq$Type extends MessageType<SendMessageReq> {
    constructor() {
        super("chatnow.transmite.SendMessageReq", [
            { no: 1, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "conversation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "message", T: () => MessageContent },
            { no: 4, name: "client_msg_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "reply_to", kind: "message", T: () => ReplyRef },
            { no: 6, name: "mentioned_user_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "forward_info", kind: "message", T: () => ForwardInfo }
        ]);
    }
    create(value?: PartialMessage<SendMessageReq>): SendMessageReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requestId = "";
        message.conversationId = "";
        message.clientMsgId = "";
        message.mentionedUserIds = [];
        if (value !== undefined)
            reflectionMergePartial<SendMessageReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendMessageReq): SendMessageReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string request_id */ 1:
                    message.requestId = reader.string();
                    break;
                case /* string conversation_id */ 2:
                    message.conversationId = reader.string();
                    break;
                case /* chatnow.message.MessageContent content */ 3:
                    message.content = MessageContent.internalBinaryRead(reader, reader.uint32(), options, message.content);
                    break;
                case /* string client_msg_id */ 4:
                    message.clientMsgId = reader.string();
                    break;
                case /* optional chatnow.message.ReplyRef reply_to */ 5:
                    message.replyTo = ReplyRef.internalBinaryRead(reader, reader.uint32(), options, message.replyTo);
                    break;
                case /* repeated string mentioned_user_ids */ 6:
                    message.mentionedUserIds.push(reader.string());
                    break;
                case /* optional chatnow.message.ForwardInfo forward_info */ 7:
                    message.forwardInfo = ForwardInfo.internalBinaryRead(reader, reader.uint32(), options, message.forwardInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendMessageReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string request_id = 1; */
        if (message.requestId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requestId);
        /* string conversation_id = 2; */
        if (message.conversationId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationId);
        /* chatnow.message.MessageContent content = 3; */
        if (message.content)
            MessageContent.internalBinaryWrite(message.content, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string client_msg_id = 4; */
        if (message.clientMsgId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.clientMsgId);
        /* optional chatnow.message.ReplyRef reply_to = 5; */
        if (message.replyTo)
            ReplyRef.internalBinaryWrite(message.replyTo, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* repeated string mentioned_user_ids = 6; */
        for (let i = 0; i < message.mentionedUserIds.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.mentionedUserIds[i]);
        /* optional chatnow.message.ForwardInfo forward_info = 7; */
        if (message.forwardInfo)
            ForwardInfo.internalBinaryWrite(message.forwardInfo, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.transmite.SendMessageReq
 */
export const SendMessageReq = new SendMessageReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendMessageRsp$Type extends MessageType<SendMessageRsp> {
    constructor() {
        super("chatnow.transmite.SendMessageRsp", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "message", kind: "message", T: () => Message }
        ]);
    }
    create(value?: PartialMessage<SendMessageRsp>): SendMessageRsp {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SendMessageRsp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendMessageRsp): SendMessageRsp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatnow.common.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* chatnow.message.Message message */ 2:
                    message.message = Message.internalBinaryRead(reader, reader.uint32(), options, message.message);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendMessageRsp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatnow.common.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* chatnow.message.Message message = 2; */
        if (message.message)
            Message.internalBinaryWrite(message.message, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatnow.transmite.SendMessageRsp
 */
export const SendMessageRsp = new SendMessageRsp$Type();
/**
 * @generated ServiceType for protobuf service chatnow.transmite.MsgTransmitService
 */
export const MsgTransmitService = new ServiceType("chatnow.transmite.MsgTransmitService", [
    { name: "SendMessage", options: {}, I: SendMessageReq, O: SendMessageRsp }
]);
