// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "transmite/transmite_service.proto" (package "chatnow.transmite", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MsgTransmitService } from "./transmite_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SendMessageRsp } from "./transmite_service";
import type { SendMessageReq } from "./transmite_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service chatnow.transmite.MsgTransmitService
 */
export interface IMsgTransmitServiceClient {
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageReq, options?: RpcOptions): UnaryCall<SendMessageReq, SendMessageRsp>;
}
/**
 * @generated from protobuf service chatnow.transmite.MsgTransmitService
 */
export class MsgTransmitServiceClient implements IMsgTransmitServiceClient, ServiceInfo {
    typeName = MsgTransmitService.typeName;
    methods = MsgTransmitService.methods;
    options = MsgTransmitService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageReq, options?: RpcOptions): UnaryCall<SendMessageReq, SendMessageRsp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SendMessageReq, SendMessageRsp>("unary", this._transport, method, opt, input);
    }
}
